### ISSUE TITLE
Update page url by adding user state as user navigates in model

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#10]
Also, extend state to store panels, panel and visualizer. -- this is pushed to later.

Use the state object that we already have.

**Comment by lattmann** [comment]
Url encoding of the state
- `project`: project name
- `branch`: branch name
- `commit`: commit hash, used if branch is not given
- `node`: object to load in the visualizer
- `visualizer`: visualizer name to open
- `aspect`: aspect name in the visualizer if applicable
- `selection`: comma separated list of selected object (node) ids

Note: Url may exceeds the maximum length limit. In the future we should be able to generate short urls and save it on server side. Server will server the state information then.

Example urls
- `/?project=test1&branch=master&node=&visualizer=ModelEditor&aspect=All`
- `/?project=test1&commit=<commit_hash>&visualizer=ModelEditor&aspect=All`
- `/?project=test1&branch=master&node=&visualizer=ModelEditor&aspect=Aspect2`
- `/?project=test1&branch=master&node=&visualizer=METAAspect`
- `/?project=test1&visualizer=ModelEditor&aspect=All&selection=%2F1801445538,%2F325565474`

**Comment by pmeijer** [comment]
It's possible to "disable" the project-browser:
1) Open up any model (in whichever way).
2) Enable split view.
3) Make the LHS window the active window.
4) Disabled split view.
5) Opening objects from the tree-browser does not change the canvas.

Notes:
6) Enabling split view again and the object from 5) will be opened in the RHS window.
7) Disable split view with RHS window as active.
8) Now the project browser's selection is respected.
