### ISSUE TITLE
Setting 'layout' in url params is lost on page load

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1006]
When setting `layout` in the url params (to use a custom layout temporarily), it is cleared when the page is loaded

**Comment by pmeijer** [comment]
Currently the layout is not part of the state (which gets serialized to the URL) and actually if you look at the startup of webgme (in `src/client/WebGME.js`) the layout loading takes place before there even exists a state.

I realize there is a need for switching layouts and will definitely look into it. If possible it should be encapsulated within the state.

**Comment by brollb** [comment]
wait - it actually currently works if you put `&layout=DefaultLayout` and reload the page (it just loses this part of the url on reload)

**Comment by pmeijer** [comment]
True it reads from the url, but you need to refresh the page to switch layout

**Comment by pmeijer** [comment]
Closed by #1040
