### ISSUE TITLE
Double click to open project throws errors

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1015]
When opening a new project from the project dropdown, double/triple clicking causes errors to be thrown. This can cause larger problems with the client if it interrupts a load/transaction, etc.

[double-click-project-list.txt](https://github.com/webgme/webgme/files/305123/double-click-project-list.txt)

**Comment by pmeijer** [comment]
Ah I see now. You mean the project dialog/modal..

**Comment by pmeijer** [comment]
Closed by #1048
