### ISSUE TITLE
Provide TypeScript Description Files for Core API

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#1016]
Although the dynamic typing of JavaScript can permit rapid development, the 
lack of static typing can be a barrier to use by developers writing plug-ins, add-ons, and visualizers.

TypeScript is a superset of JavaScript that provides type-checking.
Addition of TypeScript descriptions can be done gradually.
Incorporation of a webgme.d.ts file for the core API documentation would be very helpful.
e.g. https://editor.webgme.org/docs/source/PluginBase.html
The thing that is really giving me problems is the import of modules.

As a demonstration I would like to adapt a project I have been working on to use TypeScript.
https://github.com/phreed/webgme-immortals/tree/typescript

There are IDE for working with TypeScript (I have worked with the first two):
 * https://code.visualstudio.com/
 * https://atom.io/packages/atom-typescript
 * https://www.jetbrains.com/help/webstorm/2016.1/typescript-support.html
 * VisualStudio is also an option but it is quite different than the others and I would rather not use it.

My problems are pretty basic:
 * What files need to be added to the webgme project?
      * How are they configured?
 * What files need to be added to use the typings in my project? 
      * How are they configured?

I messed around with "Definitely Typed" and "Typed Typings" but these are for
JavaScript projects that decline to include the TypeScript definitions directly (ambient).

Here are some references that seem like they should answer these questions but I am stumped.
 * https://blogs.msdn.microsoft.com/visualstudio/2015/04/20/using-requirejs-with-visual-studio/
 * http://www.codebelt.com/typescript/typescript-amd-with-requirejs-tutorial/
 * https://blog.oio.de/2014/01/31/an-introduction-to-typescript-module-system/
 * https://www.typescriptlang.org/docs/handbook/modules.html
 * https://blorkfish.wordpress.com/2012/10/23/typescript-organizing-your-code-with-amd-modules-and-require-js/
 * https://keyholesoftware.com/2013/01/14/modularization-in-typescript/
 * http://edcourtenay.co.uk/musings-of-an-idiot/2014/11/26/typescript-requirejs-and-jquery
 * https://basarat.gitbooks.io/typescript/content/docs/project/modules.html
 * https://johnpapa.net/typescriptpost4/
 * https://addyosmani.com/writing-modular-js/

**Comment by pmeijer** [comment]
@phreed I'm not really sure what this issue covers.

**Comment by kecso** [comment]
The aim is to provide some typescript definition files within the plugin boilerplates, so that these IDEs can give better help to the developer (not just the list of the functions). 
Right now, the only way to get complete information about a function is to lookup the documentation that can be time consuming.

**Comment by phreed** [comment]
I have type definition generally working.
[webgme typings](https://github.com/phreed/typed-npm-webgme)
I have a project that I am working on (currently broken) that uses these typings.

**Comment by pmeijer** [comment]
Handled in separate project
