### ISSUE TITLE
"Error: object does not exist" when deleting node

### ISSUE THREAD

**Issue by JimnyCricket** [webgme/webgme#1018]
On deleting a node, I received the attached error. What could be causing this?
[webgme-client-dump (1).txt](https://github.com/webgme/webgme/files/308204/webgme-client-dump.1.txt)

**Comment by pmeijer** [comment]
Hey I've looked at the error dump and can't tell exactly where the issue is coming from...
Could you export the project (branch) right before the deletion and add the steps for reproduction?
Btw, are you using any custom UI components? Are you using Libraries? Thanks

**Comment by JimnyCricket** [comment]
We are working on DeepForge, and yes we have some custom UI components. I haven't seen this error in a while, so maybe it was caused by some plugins or other custom components. I'll submit a new issue if I can reproduce it.
