### ISSUE TITLE
Update header if no auth enabled

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1021]
If auth is not enabled, the project in the header should just say the name of the project rather than "guest/<project>".

Also, "transfer project" doesn't make sense if authentication isn't enabled and should probably be hidden if auth is not enabled

**Comment by pmeijer** [comment]
We will remove transfer project once the user management is done (which won't be accessible when auth is disabled).

**Comment by pmeijer** [comment]
Closed by #1022
