### ISSUE TITLE
InterpreterManager fails after uncaught exception

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1024]
When there is an uncaught exception in the project (in my case, meta editor), the InterpreterManager will also fail afterwards. It would be nice if it could fail gracefully. That is, the meta editor exception is minor and it would be nice if it didn't take out the ability to run plugins.

**Comment by pmeijer** [comment]
I'm reluctant to introduce try/catch clauses in the UI code.. Any uncaught exception will move the UI state into UNCAUGHT_EXCEPTION which implies that the user should get the error report and refresh the UI.
The underlying exception is fixed in #1025
