### ISSUE TITLE
Project history empty if no branches

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1026]
When I accidentally delete all my branches, I can't see any project history. I would expect it to at least show the loaded commit and the previous few commits
![no_commits](https://cloud.githubusercontent.com/assets/4982789/16103256/6c20e95a-333c-11e6-959e-7a870ef2e9f7.png)

**Comment by brollb** [comment]
it could just set the selection to "Recent Commits" if there are no branches/they are not on a branch

**Comment by pmeijer** [comment]
Closed by #1043
