### ISSUE TITLE
Error when merging branches - GUID Mismatch 

### ISSUE THREAD

**Issue by JimnyCricket** [webgme/webgme#1033]
Tried to merge into existing branch and got the following error. The only thing that should have changed are a couple of attributes, as far as I know.

<img width="899" alt="screen shot 2016-06-23 at 6 20 12 pm" src="https://cloud.githubusercontent.com/assets/10526094/16323346/afd226d0-396f-11e6-9e29-7c25fcb8fb9f.png">

**Comment by kecso** [comment]
is there a way to re-create the issue?
or could you provide access to the project?
(there were only two state you sent me, and that is not enough for a three way merge...)

Thanks!

**Comment by kecso** [comment]
I have checked your artifacts regarding the issue and was unable to reproduce the error.
Please let us know if you manage to reproduce the issue (and the steps leads to it).

**Comment by pmeijer** [comment]
Changing an instance of A in one branch and removing A in another results in a similar error. Instead of `undefined` the other guid is `0000-00...` though.
