### ISSUE TITLE
Exporting branch incorrectly grabs assets from blob

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1037]
I had blob assets associated w/ the model then removed the given nodes that had asset attributes and exported the branch but found that it kept exporting the project w/ the assets despite my removal of nodes referencing the assets...

**Comment by pmeijer** [comment]
Can you unzip and send the `project.json` in the exported file?

**Comment by pmeijer** [comment]
From the link you sent me: 

`https://github.com/dfst/deepforge/blob/master/src/seeds/cifar10/cifar10.webgmex`

it looks like there still are referenced assets in the model..
```
        {
            "_id": "#b014af4bf079fbd6eef2c40a8d4d2555b6643964",
            "atr": {
                "_relguid": "70cb091e462ba40fb3f8bd6f276c3963",
                "data": "c6e71c76f4bedd0b7d71b5a45b73e88c8ab28181"
            },
            "reg": {
                "position": {
                    "x": 100,
                    "y": 100
                }
            }
        },
```

**Comment by brollb** [comment]
yeah, I found them - my bad. They were just nested relatively deep in the model...
