### ISSUE TITLE
Failed branch export fails silently

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1039]
When I am trying to export the branch, it fails silently w/ the following error
[unableToSaveProj.txt](https://github.com/webgme/webgme/files/334945/unableToSaveProj.txt)

Ideally, it wouldn't fail but when it does, it would be nice to have some sort of feedback that it failed

**Comment by pmeijer** [comment]
@brollb Can you try the same action from the master?

**Comment by pmeijer** [comment]
Wait, does this still return a `.webgmex` file?

**Comment by brollb** [comment]
It wasn't returning any file... I am going to try to hunt down which project I was exporting...

**Comment by pmeijer** [comment]
I think this shouldn't be a silent error anymore. You can try it with the master.
