### ISSUE TITLE
Client error on duplicating project

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1042]
When trying to duplicate the project, I received errors about the new project not being found (which seems like it would make sense since I am creating the new project...)

[cantDuplicateProject.txt](https://github.com/webgme/webgme/files/335326/cantDuplicateProject.txt)

**Comment by pmeijer** [comment]
This should be covered by #1036 (and the associated PR at #1041)

**Comment by brollb** [comment]
ok, thanks!
