### ISSUE TITLE
executor worker should use streaming unzip

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1066]
Rather than unzipping using the system installed unzip binary, it might be more useful to use a streaming unzip such as https://github.com/EvanOxfeld/node-unzip as this would also remove the system dependency

**Comment by ksmyth** [comment]
Note it is impossible to properly extract a .zip in a streaming manner,
since the central directory is at the end
https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api

node-unzip has lots of github issues and seems abandoned

**Comment by brollb** [comment]
my bad - I see what you mean https://github.com/EvanOxfeld/node-unzip/issues/95
