### ISSUE TITLE
cached executor job gives incorrect outputNumber/stdout

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1073]
When running an executor job which has already been run (and is cached), the intermediate log info returns an outputNumber w/o the correct log output.

In my case, I am getting an outputNumber of 6 but the actual lines are `''`. It should probably return the correct line output for the job info

**Comment by pmeijer** [comment]
There is an option for setting how long the output should be stored, if it's negative it's never removed.
However when the output is cleared it should reset the outputNumber accordingly.

**Comment by pmeijer** [comment]
Closed by #1077
