### ISSUE TITLE
Model editor title not refreshed when switching project

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#11]

**Comment by lattmann** [comment]
I cannot reproduce this with 6a2542421bc85c285e42ca2749e413b0adf3c3b3 Please explain how to reproduce.

I tried:
1) open a project
2) split the Composition view
3) open a different object in each view
4) open another project (i.e. switching project)
5) the model editor gets completely reinitialized and no title is shown or left over from the previous project.

**Comment by nabana** [comment]
It's probably not an issue anymore since the refactoring

**Comment by lattmann** [comment]
Cannot reproduce.
