### ISSUE TITLE
Automerge dangling branches

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1101]
When using webgme w/ `autoMerge` enabled, merges sometimes show dangling branches:

<img width="1822" alt="screen shot 2016-08-12 at 9 41 07 am" src="https://cloud.githubusercontent.com/assets/4982789/17626548/44dbee80-6073-11e6-957e-ef6219df6454.png">

I don't see how this makes sense - the changes made on this branch are not in the ROOT node so it certainly can't be an orphan branch...

**Comment by pmeijer** [comment]
Brian can you clarify the issue here?
In general, when looking at the history it always looks better when you select a particular branch you're interested in.

**Comment by brollb** [comment]
In the diagram, it looks like the branch currently occupied started as an orphan at commit hash da5c29... However, this can't be the case as it is setting the pointer of a node that was created as some other commit in history...

What is the predecessor to that commit and why isn't it showing up? Odds are this is just a small ui thing (as the given commit is not an orphan) but it would be nice if it was clear where the commit was originating from...

**Comment by pmeijer** [comment]
Can you reproduce this? I think we had a talk about this a while back..

**Comment by pmeijer** [comment]
Closing this as it doesn't seem to happen anymore..
If it does, please reopen.
