### ISSUE TITLE
Future times in the project history

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1103]
Some commits in the project history state "in X minutes" which doesn't make any sense. These also will sometimes have predecessors that happened earlier:

<img width="1822" alt="screen shot 2016-08-12 at 9 42 24 am" src="https://cloud.githubusercontent.com/assets/4982789/17626551/44de0f58-6073-11e6-96bc-cb10529d78a8.png">

In the next image, the latest commit (causally) occurred "a few seconds ago" but the previous commit is going to happen in 5 minutes...
<img width="1805" alt="screen shot 2016-08-12 at 9 47 34 am" src="https://cloud.githubusercontent.com/assets/4982789/17626549/44dcc1b6-6073-11e6-98d0-80392d7f3f64.png">

**Comment by pmeijer** [comment]
The timestamp is generated by the clients at the time they persist and invoke makeCommit. I haven't seen commit being off by minutes, but have seen seconds. Looking at the history it looks like the commits with negative time are made on the server. Is your browser running on the same machine? Or could it be that the system times of the two computers really are off in minutes?

When the commits are ordered they are firstly ordered in terms of parent/child relation and secondly ordered in terms of timestamp.

**Comment by brollb** [comment]
I am going to close this issue since it is due to incorrect system time
