### ISSUE TITLE
update library from seed

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1105]
It would be nice if the library api supported updating from a seed.

I like providing dsml's as a seed which is included in the main seed as a library bc:
- it is included in the project's version control
- it can be updated (as opposed to simply providing it as a seed)

**Comment by kecso** [comment]
could you please describe your use-case in details?
which API you meant? (UI or the client or the core)
thanks!

**Comment by brollb** [comment]
In my use case, I am providing the user w/ a seed called "project" which contains two dsml's: `nn` and `pipeline` which have matching seeds stored w/ the project (though they are filtered out from the ui's seed list).

When there are updates to the `pipeline` and `nn` projects, I would like people to be able to update their libraries to the latest versions of `nn` and `pipeline` (stored on the server like the seeds) from the browser ui. Ideally, the main page would check if the libraries are out-of-date and create a toast that allows them to update them.

**Comment by kecso** [comment]
We do not have a generic way of dealing with versioning of files.
We can add the 'seeds' as new sources for libraries, but in your case it would be a half measure only (and they can be used as library sources right now, though it is not that straightforward).
I would suggest a plugin, that could run on the server, check the version of the seed, and execute a library update (and put its execution behind a custom button).
