### ISSUE TITLE
ProjectNavigatorController fails on new project created elsewhere

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#111]
Repro:
Open WebGME in two tabs
Tab1: Open Manage Projects... dialog
Tab2: Create project
Tab1: Refresh. Open new project
Tab1 breadcrumb does not open. console shows this message twice: "Test_33697 does not exist in the navigation barProjectNavigatorController.js:836 ProjectNavigatorController.selectBranchProjectNavigatorController.js:232 (anonymous function)EventDispatcher.js:100 hEventDispatcher.js:86 EventDispatcher.dispatchEventclient.js:684 branchWatcherclient.js:917 (anonymous function)failsafe.js:302 (anonymous function)client.js:652 (anonymous function)socket.io.js:2253 SocketNamespace.onPacketsocket.io.js:1930 Socket.onPacketsocket.io.js:1332 Transport.onPacketsocket.io.js:1303 Transport.onDatasocket.io.js:2378 websocket.onmessage

**Comment by pmeijer** [comment]
Resolved in #517
