### ISSUE TITLE
Error renders projects unuseable

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1111]
After updating a plugin to update cache, root node and active node (#1102), then running the plugin and editing the project with the web ui, opening the project throws the following errors:
```
logger.js:66 hashUpdateHandler invoked loading and it returned error #f903c737d0a46413fbbea5cd956c2f93157eb379 TypeError: Cannot read property 'base' of null(…)
```
I have attached the rest of the logs: [cant_open_proj.txt](https://github.com/webgme/webgme/files/423034/cant_open_proj.txt)

After throwing these errors, it will not allow me to open the given project (hence the unuseable)

**Comment by kecso** [comment]
After checking the details, it turned out that the plugin corrupted the commit, that caused the given project to become unusable (old versions were still loadable).
