### ISSUE TITLE
Notify user on reconnect on executor worker

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1114]
When the executor disconnects, it prints a bunch of error logs about not being able to connect to the server. When it reconnects, it is silent but as there can be a lot of logs, it is not always obvious that the executor isn't still trying to connect (the error logs very quickly take up the whole terminal).

It would be nice if it displayed a "connected" message of some sort on connection.

**Comment by pmeijer** [comment]
Closed by #1142
