### ISSUE TITLE
UI not showing branch deleted

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1121]
Sometimes when deleting a bunch of branches, the dropdown still shows the branches exist until a refresh.

**Comment by brollb** [comment]
I don't know of a good way to replicate this currently

**Comment by pmeijer** [comment]
Trying this with deletion (and creation too) of 100 branches (in a burst) I cannot reproduce it.

**Comment by pmeijer** [comment]
Cannot reproduce
