### ISSUE TITLE
node not deleting using the `client`

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1122]
I was just using the client to set some attributes on a node then delete the given node but the node seems to sometimes be deleted and sometimes still exists w/ the attribute changed...

**Comment by kecso** [comment]
Could you give a bit more detailed description of the issue?
How do you experienced the node being 'still' there? (after making the commit and reloading)
Have you been using a transaction or you made the changes in a burst?

**Comment by pmeijer** [comment]
Could this be related to #1161 ?

**Comment by brollb** [comment]
So this shouldn't be related to #1161 since I was able to set the attribute. Unfortunately, I don't remember exactly what I was doing to cause this issue. If it works in a single transaction, then we can probably close it for now

**Comment by kecso** [comment]
Is there any chance that the node you tried to remove was created programmatically, without a base node?
Have you experienced it since?

**Comment by kecso** [comment]
I will close the issue.
Please reopen it if the situation reoccures.
