### ISSUE TITLE
Projects dialog does not block enter pressing when entered project collides with existing one.

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1138]
Invalid project names should not allow the user to click the enter/continue button. Since they currently can, the error shows up on the server saying that it cannot create the given project

**Comment by pmeijer** [comment]
Which UI piece is this? The ProjectsDialog should guard against invalid project names..

**Comment by brollb** [comment]
it doesn't if you press "enter"

**Comment by pmeijer** [comment]
Closed by #1140
