### ISSUE TITLE
executor worker info

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1144]
It would be nice to know things like:
- how many workers are connected
- how many have jobs

and other metadata

**Comment by pmeijer** [comment]
Have you tried the `/workers` enpoint?

**Comment by brollb** [comment]
what's the exact endpoint? I am getting 404 for `<url>/workers`

**Comment by pmeijer** [comment]
oh sorry that was the relative one from the executor.. 
`/rest/executor/worker`

Example: `{"pmeijer-Desktop_8508":{"clientId":"pmeijer-Desktop_8508","lastSeen":1472754827.505,"labels":[],"jobs":[]}}`

**Comment by pmeijer** [comment]
This feature already exists
