### ISSUE TITLE
WebGMEGlobal not defined under ng-gme

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#115]
It appears only src/client/js/WebGME.js defines WebGMEGlobal.config on the client side. This breaks the new key generator under ng-gme:

    return function KeyGenerator(object){
      if(keyType === null){
        if(WebGMEGlobal && WebGMEGlobal.config && typeof WebGMEGlobal.config.keyType === 'string'){

**Comment by ksmyth** [comment]
Sorry I did not post the original error message.

ed92f02 does not fix the issue. WebGMEGlobal is not defined, so it raises a ReferenceError

    ReferenceError: WebGMEGlobal is not defined

    Call Stack
    Async
    key.js:26
    KeyGenerator
    coretree.js:711
    __saveData
    coretree.js:692
    __saveData
    coretree.js:692
    __saveData
    coretree.js:692
    __saveData
    coretree.js:692
    __saveData
    coretree.js:728
    persist
    future.js:113
    unadapt1
    client.js:1464
    saveRoot
    client.js:2144
    setAttributes
    NodeService.js:369
    NodeObj.setAttribute
    app.js:142
    setattr
    angular.js:13170
    processQueue
    angular.js:13186
    (anonymous function)
    angular.js:14383
    Scope.$eval
    angular.js:14199
    Scope.$digest
    angular.js:14422
    (anonymous function)
    angular.js:4902
    completeOutstandingRequest
    angular.js:5282
    (anonymous function)

I think you should write this instead: `if (typeof WebGMEGlobal !== 'undefined' ....`

**Comment by kecso** [comment]
Thanks!
Yeah I realized atfer the commit and Patrik's comment, that the issue is most probaly that it crashes...
Working on it.
