### ISSUE TITLE
SplitPanel blocks certain mouse events, don't call event.stopPropagation()

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1151]
What is the purpose behind the `mousedown` interaction stopping its propagation?  This blocks certain events from ever reaching children (e.g. visualizers) that might be used by other libraries.  I have tested to show that (as far as I can tell) removing that call (tested by removing it from `webgme.dist.build.js` in my `node_modules` folder) does not affect the behavior of webgme and does allow the propagation (and thus the correct application behavior).

For reference, the code which performs the action in question is found here:

https://github.com/webgme/webgme/blob/b7756cc52bde13d9ed6d9c1c2cf0987528184ed6/src/client/js/Panels/SplitPanel/SplitPanel.js#L77

and here:

https://github.com/webgme/webgme/blob/b7756cc52bde13d9ed6d9c1c2cf0987528184ed6/src/client/js/Panels/SplitPanel/SplitPanel.js#L82

**Comment by pmeijer** [comment]
Closed by #1156
