### ISSUE TITLE
Zoom-based User Interface

### ISSUE THREAD

**Issue by mchogan** [webgme/webgme#116]
I'm not sure how to contribute to the wiki or where to contact the team, so I'm filing an issue for now. I've been away from GME for a while, but have 4+ year of experience using it to architect embedded systems software. Very excited to see a web edition!

Gliffy and Lucid Chart are great, but Zoom-based user interface is another metaphor that needs to be considered (Wikipedia)[http://en.wikipedia.org/wiki/Zooming_user_interface]. For GME specifically, as users zoom deeper into a model they need a way to allocate connections between model components to increasingly granular components. As users zoom out, they need to visualize relationships between high-level abstracted components. This would allow for top-down design that begins with abstract composite model components and refines those into atom level components over a series of design iterations.

Mapping software is the best ZUI I have used to date. At a high level I can see a route between two regions or states, but if I zoom in then I can see specific roads and relationships between towns or even homes. The ability to present abstract and detailed views of the geospatial model aids people planning a trip, first conceptually and then at an implementation level of detail.

**Comment by lattmann** [comment]
__Contribution__: We are currently refining our internal development process to accommodate external contribution. Once we are done, information will be posted.

Filing an issue is the best way for now. This way nothing will be lost. We try to reply to all requests.

__ZUI__: This is a good idea; we have also considered it. This will be a long term plan.

**Comment by mchogan** [comment]
Worth a look at how Facebook is using Origami for UI prototyping. There aren't many good examples of combining the disciplines of MIC and UI design and this seems to be one.
https://vimeo.com/facebookorigami/videos

**Comment by mchogan** [comment]
GoJS offers some UI examples that are relevant to MIC. This library is more inspirational than useful, since it is commercial, not FOSS.
http://gojs.net/latest/index.html?gclid=CK7nnKrNlMQCFYhgfgod0VoAJg

Of note:
* [Regrouping](http://gojs.net/latest/samples/regrouping.html), interesting because it might allow for handling abstraction and composition of system elements
* [Dynamic ports](http://gojs.net/latest/samples/dynamicPorts.html), most interesting for the way custom connector routing is handled
* [Navigation](http://gojs.net/latest/samples/navigation.html), interesting as an enhanced relationship exploration mode

**Comment by mchogan** [comment]
Unreal Engine [Blueprint Visual Scripting](https://docs.unrealengine.com/latest/INT/Engine/Blueprints/index.html) may be the most successful professional-level application of visual programming that I've come across. C++ components are exposed as Blueprint components. It seems that artists and designers are successfully using this system to make quite a bit of progress without understanding traditional, text-based development.

**Comment by mchogan** [comment]
[Lego Mindstorms](http://www.lego.com/en-us/mindstorms/learn-to-program) uses a block-based visual programming paradigm that's also gotten out there quite a bit.
