### ISSUE TITLE
Can't delete nodes that aren't loaded w/ the client

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1161]
calling `client.delMoreNodes(ids)` w/ ids that have not yet been loaded results in the nodes not being deleted

**Comment by pmeijer** [comment]
The nodes need to be loaded before you delete them. 
We could look into exposing the `deleteChild` method on the core that only requires the parent to be loaded. (The parent would always have to be loaded though, since it will be modified at the point of deletion).

**Comment by brollb** [comment]
thanks - that did the trick!
