### ISSUE TITLE
Sometimes when starting server it never comes up

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1169]
When it fails, there are no errors and it does not crash, you just never see the `Server is listening...` message so you cannot connect. After a random amount of `ctrl+c` & restarting the server (i.e. restarting the server a random amount of times) at some point the message will show and you'll be able to connect to the server.  No errors are produced.

**Comment by finger563** [comment]
Some point in the near future I'll get you those logs showing what's happening when I see this.  Can you post here the setting needed to get the extended socket logs or whatever it was you mentioned?

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/blob/master/config/config.default.js#L127

Push a new file logger to it
```
{
    transportType: 'File',
        options: {
            name: 'debug-file',
            filename: './server-debug.log',
            level: 'debug',
            json: false
         }
 }
```

**Comment by pmeijer** [comment]
This seem to have to do with the custom svgs.

**Comment by finger563** [comment]
Can confirm, when removing many of the svgs, the issue seems to disappear.
