### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by mchogan** [webgme/webgme#117]
Is there only one tutorial video? Can I use the old GME tutorials with WebGME? It would be great to have a tutorial that shows how to use GME to represent a basic web service or some useful bit of capability that can be integrated into a real-world website (maybe implement a jQuery widget) or a Unity3d game (JavaScript, not .net).

**Comment by lattmann** [comment]
Right now there is only one video tutorial.

No you cannot use the desktop GME tutorials for WebGME. The docs/tutorial.html can be used and it is a good starting point in addition to the video, but it has screenshots from an older version of the user interface.

We will use domains as examples, which our developers are familiar with. Pull requests of examples (i.e. use cases) will be accepted in the future after the first examples are created in the repository.
A few examples are available in [webgme/webgme-domain-tools](https://github.com/webgme/webgme-domain-tools) `example_projects` including:
- meta models
- examples models
- example plugins (i.e. model transformations)
- example decorators to change the graphical representation of domain specific objects

Note: check config.json before you start the app. MongoDB and http port may need to be changed.
If you would not like install anything on your machine, then you can check [webgme.org](http://webgme.org) and click on try now. There are three good (read-only) examples: Logic Gates, Petri Nets, and Signal Flow Processing.

We are planning to create documentation and tutorials in this repository (most likely) during this summer. This issue remains open and will be scheduled for a milestone.

**Comment by lattmann** [comment]
@mchogan tutorials were posted here: https://www.facebook.com/WebGME/posts/1774280379472709

@pmeijer can we close this issue now? Should we add more links to documentation/tutorials?

**Comment by pmeijer** [comment]
Our youtube channel is here:
https://www.youtube.com/channel/UC1cPQP4jjsXRhpXUnoPZQWg
