### ISSUE TITLE
fsyncDatabase must be serialized

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#118]
With webgme-cyphy perfTest and webgme branch bug/118 you can see this from the server:

    #fc08a0c93835d7a734a71421af853c14a17d02e1  ->  #04a57e1d690f47e7768335c18121d9baf946e44f
    #04a57e1d690f47e7768335c18121d9baf946e44f  ->  #fbb9b940e67515c48f9bc8e79e1ea89f57453cf4
    #fbb9b940e67515c48f9bc8e79e1ea89f57453cf4  ->  #39aba1e6e3c87bfa9822ba1d1881ce2d62d12e42
      #04a57e1d690f47e7768335c18121d9baf946e44f  ->  #fbb9b940e67515c48f9bc8e79e1ea9f57453cf4
      #fc08a0c93835d7a734a71421af853c14a17d02e1  ->  #04a57e1d690f47e7768335c18121dbaf946e44f
      #fbb9b940e67515c48f9bc8e79e1ea89f57453cf4  ->  #39aba1e6e3c87bfa9822ba1d1881ce2d62d12e42

fsyncDatabase makes the setBranchHash updates be out-of-order. The callbacks given to fsyncDatabase should be serialized.

**Comment by kecso** [comment]
I will try to reproduce it.
Just one quesiton: are the setBranchHashes failed? - the user forked -
And how and where did you get this output? I mean if it is setbranchhash data output, then it is wierd that the exact same transition was sent twice (no user could done that...)

thanks

**Comment by kecso** [comment]
Ohh, I see now!
So the first three is the request (in order), and the final three is the response (in a wrong order).
Then please disregard my second question.

**Comment by ksmyth** [comment]
I fixed this issue in dbd17358
