### ISSUE TITLE
Use keepalive in BlobClient

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#119]
Uploading many small files can be slow with the TCP creation/teardown overhead for each file, especially if the GME server is far away from the client. (Double especially if using https)

This stackoverflow answer has some hints on how to do it with superagent:
http://stackoverflow.com/questions/20743546/keep-alive-connection-with-superagent

**Comment by lattmann** [comment]
Assuming that this setting is not enough:
```
request
.get('localhost:1337/helloword')
.set('Connection', 'keep-alive')
.end(function (err, res) {
   console.log(res.text);
});
```

If we would use `agentkeepalive` node-module, how would that work in the browser?

BloblClient module should work from nodejs and from web browsers.

**Comment by lattmann** [comment]
Related to #225

**Comment by lattmann** [comment]
- Use agentkeepalive@0.2.4 for node and node-webkit
- For browsers HTTP 1.1 has connection header set to keep alive by default
- blob client has a new options parameter `keepaliveAgentOptions` see the source code for the default values.

See screenshot, which captures the server side blob test execution. It shows that within the same TCP stream BlobClient makes multiple requests.

![blob_server_side_tests_keep_alive](https://cloud.githubusercontent.com/assets/1108945/6928851/7febfa24-d7bc-11e4-8bf9-f63edf027f22.png)

**Comment by ksmyth** [comment]
I also verified that it works for https on Windows v0.10.36
