### ISSUE TITLE
Allow meta relations to be renamed

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#1194]
Provide a mechanism to rename meta-relations.
This would include: pointers and sets.
![image](https://cloud.githubusercontent.com/assets/211644/19092551/cb20be5a-8a4c-11e6-9dcf-1b7bb1fdfebd.png)
The example has a set relation called 'quantifies'. Suppose some partners want it to be called 'applicable resource'.

**Comment by phreed** [comment]
De-conflating the meta-relation alias/identifier would make changing the alias trivial as it would only be stored in one place (the meta-rule). 
Naming Rule: It is a "design-smell" when the identifier and alias/name are conflated for an object.

**Comment by pmeijer** [comment]
Typically changes in the meta requires changes across projects and would need a migration script/plugin. 
As I mentioned before we could consider adding an asynchronous task for renaming meta definitions, e.g. sets, pointers, attributes etc, that propagates the changes downwards the inheritance chain. This could potentially be used both from the UI and as an API call for migration scripts.
Not sure if it's a design smell though. If you rename a method or field on a class or prototype in any programming language - the derived classes aren't automatically updated. Nor do you keep aliases for them.

**Comment by pmeijer** [comment]
Closed by #1477
