### ISSUE TITLE
When defining connections, have the ability to assign a color or some other visual attribute

### ISSUE THREAD

**Issue by DWatkins** [webgme/webgme#1204]
It would be nice to have some way to visually distinguish connections from each other. i.e. if a component has multiple different connections, changing the color of the lines or something similar.

**Comment by pmeijer** [comment]
Currently you can select the color of the meta-type node and when a new connection of that type is created it will be colored the same way. 
You can also set the color of the individual connection instances in the instance model. 
if this is what you mean, you simply select the connection (in either case) and pick the color clicking the droplet in the header toolbar.

**Comment by DWatkins** [comment]
This is an example model, with two types of connections, `score` and `comparison`

![image](https://cloud.githubusercontent.com/assets/455381/19336614/8c9087d8-90d2-11e6-9220-d9636e002c1c.png)

Here is is the meta-model

![image](https://cloud.githubusercontent.com/assets/455381/19336653/c53316e6-90d2-11e6-80e0-4885c6f8e93f.png)

I believe I have done what you suggested and colored the connection's meta nodes, but all connections in my model are still black.

Am I doing something wrong?

**Comment by pmeijer** [comment]
I do realize it might not be that obvious, but when you select the color in meta-editor - the colors are only changed for the object on the meta-sheets. You need instead select the connection in the composition editor and set the color from there.

**Comment by DWatkins** [comment]
Ah. I see. I change the color of the node in my language, not in the meta. This works now. Thanks.

![image](https://cloud.githubusercontent.com/assets/455381/19336998/1e0a06b4-90d6-11e6-968d-f2e0d85c3ebe.png)

**Comment by pmeijer** [comment]
This feature is available
