### ISSUE TITLE
Installation instructions for webgme-cli

### ISSUE THREAD

**Issue by sprinkjm** [webgme/webgme#1221]
I am having trouble understanding the instructions from the readme, specifically the 'this' pointer from the following statement:

> Options to deploy and run WebGME:
> 
> webgme-cli. This is the preferred way of using webgme as it allows you to:
> 
> Automatically generate boilerplate code for extension components (w/o manually configuring paths etc.).
> Reuse components from other users.
> Publish and share your work with others.
> Updating to newer webgme releases only requires a npm install webgme and won't cause any conflicts.
> For webgme developers, clone this repo.
> 
> install packages with npm npm install
> launch mongod locally
> start the server npm start

"For webgme developers, clone this repo" -> is 'this' webgme/webgme or webgme/webgme-cli?

**Comment by pmeijer** [comment]
That is the webgme/webgme repo. By "webgme developers" is meant developers that are making changes to the actual webgme core functionality (not adding their own customization).

**Comment by pmeijer** [comment]
Basically the path to use webgme is to install webgme-cli as a global node-module
```
npm install -g webgme-cli
```

After installation `webgme` should be available as a command, to check that it installed properly do `webgme --version`. This tool can be used to initialize a new configurable/extendable webgme deployment. In an empty directory named appropriately simply do: `webgme init` and follow the instructions.

Related issue in webgme-cli repo:
https://github.com/webgme/webgme-cli/issues/199
https://github.com/webgme/webgme-cli/issues/200
