### ISSUE TITLE
Multiple locations added to browser history per one user action

### ISSUE THREAD

**Issue by appersonj** [webgme/webgme#1226]
Example, using the LogicGates Demo (mentioned on ) 
Follow the link:  https://editor.webgme.org/?project=demo%2BLogicGates&visualizer=ModelEditor&layout=DefaultLayout

Now (in chrome or firefox) press [left-button]-back-arrow
You will see 4 Items on the history list, all marked "demo/Logic Gates"

If you now double-click on the top-left Nand gate, you will find 8 items in the history list

Ideally, (only)  each USER action should displayed and (only) each USER action should be reversible, without forcing the user undo multiple inferred choices.

**Comment by pmeijer** [comment]
Closed by #1253
