### ISSUE TITLE
Fail gracefully when can't find asset

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1255]
When exporting a project w/ hash-like attributes (such as executor job id), exporting the project fails:
```
[gme:server:worker:simpleworker:pid_11023:WorkerFunctions] exportProjectToFile failed with error Error: gathering assets [d37cb704812a3a2f70a9dbeb979769367d3de4ff] failed:Not Found
...../node_modules/webgme/src/common/blob/util.js:200:35
```

This prevents me from exporting the project... This should simply warn (probably in the console) or just do best effort.

**Comment by pmeijer** [comment]
Closed by #1257
