### ISSUE TITLE
Worker doesn't detect SIGINT as exit code 130 on *nix

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1262]
When the job for the worker requires cleanup before exiting, the job for the worker can override the exit event handlers and the `SIGINT` event (in case it is canceled from webgme):

```
process.on('SIGINT', function() {
    // Clean up code for the job
});
```

However, this can lead to a problem since calling `process.exit` will no longer show the job was canceled using `SIGINT` (the worker checks the signal to see if the job was canceled which will be null).

In *nix, exit code 130 corresponds to `SIGINT`; recognizing this in the worker should solve this problem.

Some examples of failed work-arounds:
```
process.on('SIGINT', function() {
    process.exit(130);  // returns exitCode=130; signal=null
});

process.on('SIGINT', function() {
    process.exit('SIGINT');  // returns exitCode=0; signal=null
});

process.on('SIGINT', function() {
    process.exit();  // returns exitCode=0; signal=null
});
```

**Comment by brollb** [comment]
I just realized this issue should probably be in the new [executor-worker](https://github.com/webgme/executor-worker) repo..

**Comment by pmeijer** [comment]
Closing it here as the PR in [executor-worker](https://github.com/webgme/executor-worker) has been closed
