### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by lattmann** [webgme/webgme#129]
Sometimes mongo tests are marked as failed. I believe the tests are not implemented correctly.

[Link](https://travis-ci.org/webgme/webgme/builds/49912653) to such a build job. Same source code built twice where one failed and the other one succeeded.

**Comment by kecso** [comment]
according to the linked build:
- I think the test is not wrong, simply it seems the behavior of the mongo driver changed from node 10 to node 11 (check the logs)
- the failing case was built for showing that it is possible to screw up object insertion order (the logs still show that the order is changed, but somehow the last one which was checked happens at the end of the insertion queue)
- on the other hand you are right that the case should be enhanced to still show that order do get mixed up
- or we can say that it is a fact that insertion order is unpredictable and we only test that in case of fsync we can be sure that everything is in the database.

**Comment by lattmann** [comment]
Merged with #135
