### ISSUE TITLE
support for quick way to test app inside docker

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#1372]
Would be nice to have a quick way to run  webgme-app inside a docker container to test the functionality of the app.
Scenario: Found a nice webgme-app and want to run it to see the functionality.
A docker scenario would be nice to run such app, so that one doesn't necessarily has install it on the host machine.

**Comment by pmeijer** [comment]
Such a webgme-app would need to create an image using a recipe like this one

`https://github.com/webgme/vulcan-embedding/blob/master/Dockerfile`

where the references config file is here:

`https://github.com/webgme/vulcan-embedding/blob/master/config/config.docker.js`

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/wiki/Dockerized-WebGME
