### ISSUE TITLE
Feature Request: allow support for custom constraints other than javascript in the meta

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#1374]
currently the constraints that can be encoded are only javascript. 

A dropdown option to select whether to use javascript or custom constraints will be useful feature. 
Users can then parse these custom constraints in the plugin to test the validity using user specific tools.

**Comment by pmeijer** [comment]
If I interpret your request correctly.. you're looking for a way to edit code like properties/attributes on meta nodes only.

With #1482 and #1483, this behavior can be obtained by adding an attribute as `multiline` and setting it as `readonly`.
