### ISSUE TITLE
Socket.io writes log messages that are not stored in the server log.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#138]

**Comment by pmeijer** [comment]
Probably these should be stored in a separate log.

**Comment by pmeijer** [comment]
The was due to me having the older socket io version on my machine. Cannot reproduce.

**Comment by kecso** [comment]
Additionally, in the new socket.io implementation, the whole loggin mechanism have been removed so the server logs will not have any text from the transport protocol layer.
