### ISSUE TITLE
Provide interface within a project to see what data is saved for the logged in user

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1384]
Would make it easier to customize / see what visualizers and other components save, and allowing modification would enable fixing / debugging problems that may crop up :)

**Comment by pmeijer** [comment]
Unless you mean GUI piece there is a REST endpoint at `/api/user/settings`

**Comment by finger563** [comment]
yea I was meaning a GUI piece, probably in the control panel for the user?

**Comment by pmeijer** [comment]
This has been added to the user-management page (for site-admins.) Setting Wontfix as it isn't fixed in this repo.

**Comment by finger563** [comment]
So has this user management page been rolled out into 2.15.x?
