### ISSUE TITLE
Add support for more clearly specifying the inheritance when creating object instances that involve mixins.

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1433]
Similar to how pointer objects are handled. 

When creating pointers, you can drag an existing object onto the canvas of another object and if there are multiple child types whose pointers can point to the dragged object, a context menu will be created to allow you to select which object type to create (or which pointer to set in the case you're setting a pointer on a drag target object which has multiple pointer names that can point to the dragged object).

In the case that you have an object which inherits from multiple base objects (through the use of mixins), it would be good to select which branch of the inheritance tree to use when dragging that object in, and then to use those specific containment rules defined by that branch of the inheritance tree.

I realize that the UI might get kinda hairy here w.r.t. knowing which branch the object came from after it was created (since the UI only shows the closest base node and meta-node), but that also provides a reason to improve that part of the UI so you can see exactly what the inheritance tree for each selected object is :)

**Comment by pmeijer** [comment]
The mixin concept does not introduce multiple inheritance. A node still has a single base, however meta nodes can use mixins to "include" meta definitions from multiple sources.

https://en.wikipedia.org/wiki/Mixin

I might be misinterpreting what you're looking for here though.

**Comment by finger563** [comment]
In that case, why am I able to create an object C as a child of D, when D only defines containment over B, and C only contains mixin of B?  (I like that I can do this, but it seems like that shouldn't be the behavior if I understand what you're saying correctly)

**Comment by pmeijer** [comment]
Maybe it's an abuse of the concept of containment - but it's treated as a bidirectional relationship in that 'canContain' and 'canBeContained' are propagated the same way.

**Comment by kecso** [comment]
I believe it is in line with the Meta rules in general and the mixin concept.
When you set that D can contain B, you say that D can contain anything that is of 'type' B. When you set B as a mixin of C, you set that C can/should behave as B (like implementing an interface).
Therefore C can be contained in D.

**Comment by finger563** [comment]
Since that's the case, a node could have multiple inheritance paths to inclusion as a child of another node (since as in my case the meta rules might only be propagating through mixins), so can we have a similar context menu to select which type of object we're creating? I realize it's more complicated because it's not a single element but rather selecting between tree branches, but having a way to visualize such branches would also be useful in other parts of the UI I think :)

**Comment by pmeijer** [comment]
The thing is that there is only one containment in webgme. All that multiple definitions does - is giving the option to constrain the cardinality of specific types.
I know it works differently in UML.

**Comment by pmeijer** [comment]
The way around this is to create new meta-types that mixes in the common properties. Worse case they would have to define the properties themselves and just mixin nodes to have a common type (same answer to `isTypeOf`).
