### ISSUE TITLE
Syncing model overwrites changes that have not been committed

### ISSUE THREAD

**Issue by DWatkins** [webgme/webgme#1434]
When updating a model with other changes underway, such as multiple users editing the same project, any unsaved changes are lost.

Example: Edits to a text field in the property editor are lost if the project refreshes due to another user making a change.

**Comment by DWatkins** [comment]
Further use seems to show that it's only text fields that are reset.

**Comment by pmeijer** [comment]
Thanks, I think the key here would be to not update (or refresh) any text-fields when they are focused.

**Comment by DWatkins** [comment]
This issue still occurs in v2.19

**Comment by pmeijer** [comment]
#1437 should have fixed this for the property editor and it worked for me just now. In which places does it happen?

**Comment by DWatkins** [comment]
I am encountering this behavior when editing a text field in the property editor and a change to the model (such as clicking and dragging an object) occurs within the same branch.

It does require two browsers on two separate computers to replicate, since clicking into a second tab on the same browser changes the focus of the cursor and causes it to autosave.

Replication steps:


  1.  Select a single line attribute, and modify it in some way. Don’t press enter or click away.
  2.  Without moving the attribute out of focus, navigate to the same branch on a separate computer.
  3.  Perform some action that initiates a commit, such as clicking and dragging an icon.
  4.  The attribute in the first browser will reset to its original value.

Dexter Watkins

________________________________
