### ISSUE TITLE
Dockerfile support

### ISSUE THREAD

**Issue by lazydino** [webgme/webgme#1458]
Hi,
 Is there an 'official' supported version of Dockerfile? There are several ones found on hub.docker.com, and I also found one in the 'bcrypt' branch of this repos. Any doc about it?

**Comment by lazydino** [comment]
Did not go through doc carefully, will read https://github.com/webgme/webgme/wiki/Dockerized-WebGME

**Comment by pmeijer** [comment]
lazydino, yes we currently haven't seen the use-case of publishing the "barebone" webgme app as a docker image. Typically webgme is used together with a defined meta-model together with custom visualization, model interpretation/transformations.. 
The link you found gives the pointers to what such an app would have to consider when running within a dockerized container.

**Comment by pmeijer** [comment]
We've uploaded an official image at:
https://hub.docker.com/r/webgme/webgme-org/

**Comment by lazydino** [comment]
Thanks! Is the Dockerfile available for the public to download?
