### ISSUE TITLE
enhancing object search 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#1460]
When once tries to search for an object using the search bar on the top panel, it only searches for the object in the current sheet. Will be good have an option wherein it shows list of all the objects in the project

**Comment by finger563** [comment]
Isn't this handled by the search that exists in the tree browser?

**Comment by yogeshVU** [comment]
Oh.. I just noticed the the search button. I think would be nice to have a 'lens' icon for the search feature, so that it is easy to notice .

**Comment by kecso** [comment]
If we are talking about a global search-by-name function, that is not really feasible. The main point of WebGME is that you do not have to have all the nodes downloaded to the client.
One option would be to introduce a server task, that could locate a node given its name (though it would not be really usefull, or would hard to use it in a way that you start to write the search string and it will show you all the nodes that has it...).
As an extension, I can see that we can allow search among all currently available nodes via the client API.
That would be a step closer, but still limited...

The current search'es' are:
- the magnifying glass and text field searches among the visualized nodes, as they are available
- the 'target' icon does not search, but locate the selected item in the tree browser (and do it in steps...)
- the 'filter' function in the tree browser could also be used as a form of search, but again, it can only function on the opened branchs of the tree...

**Comment by pmeijer** [comment]
We've also started on this;

https://github.com/webgme/graph-queries

If it's something that could be useful - we can complete the auto syncing portion of it. Please post issues at the repo.
