### ISSUE TITLE
Automated dangling connection removal

### ISSUE THREAD

**Issue by kecso** [webgme/webgme#1465]
In some domains, the connection that does not have valid endpoints do not make sense, and should be removed, otherwise it can confuse the end-user.
As this is not true to all domains, it should not be a Core functionality, and be configured on project kind or project Id basis.
Therefore an extra component option for the ModelEditor would be sufficient (and the implementation could also functions as a blueprint for other visualizers) to control if the visualizer should automatically remove if it discovers a dangling connection.

**Comment by finger563** [comment]
Why would this be on the modelEditor and not on the server side?  Say I don't use the modelEditor visualizer but still want that functionality?

**Comment by kecso** [comment]
The issue with a server side solution of the problem is that the server doesn't load the nodes. So it could only be done in an addon fashion, but that would add too much extra time after each commit (as you might have to discover the instances of the just removed endpoint of the connection, or you have to discover all connections after every commit).
So the easiest is always during load, therefore doing it on the client side.
Unfortunately, the Core does not know about the project kind, which is essential as the global option would be harsh in most cases and the by projectId option would be cumbersome to set (not to mention that it would be difficult to introduce into any configuration that is currently available for the Core).
So that is why the obvious choice falls to component configuration and the introductory component ModelEditor.

On the other hand I do agree with you, that it would be better addressed on a more global level (like the Client). I will check the possibility of a configuration that would be tied to the Client.

**Comment by pmeijer** [comment]
There is a decorator for this at:
https://www.npmjs.com/package/webgme-connection-remover
