### ISSUE TITLE
Feature request: Enable model read-only plugin execution

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#1466]
Will be good to have a model read only plugin execution functionality. 

Usecase: if one runs non-trust worthy plugin, and do not want to give write access to the model, then will be good to have a write, read flags settings when executing an unknown plugin.

May be useful when working with library functionality

**Comment by finger563** [comment]
If I understand correctly, this already exists as you can set the `writeAccessRequired` parameter of your plugin:

https://github.com/finger563/webgme-hfsm/blob/master/src/plugins/SoftwareGenerator/metadata.json#L12

**Comment by pmeijer** [comment]
At the point of invocation you can omit to pass a branch and that way there won't be any updates in the model (more than a head-less commit). 
I think calling non-trust worthy plugins is a bad idea. You probably mean a plugin that you cannot modify without editing other's code (for instance an imported plugin).
For this case you could subclass that plugin and bypass the save call. Or you can wait till next release where you will be able to easily call plugins from within plugins and only get a record of attempted saves (persists/commits) and you can decide whether to actually save or not from the caller plugin.
