### ISSUE TITLE
Feature Request: UI: allow full-screen the current active split panel without destroying all other split-panels

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1479]
Would allow us to temporarily "maximize" / focus on a single split panel without permanently removing the context provided by the other split panel instances.

**Comment by kecso** [comment]
Could you elaborate a little bit?
So would it be a full-screen (the only thing visible), or just maximized so the single split panel would fill the complete space of the visualizer space?

I believe both have their ups and downs, but probably the second one is more useful (given that you still want to have all functionality at hand).

**Comment by finger563** [comment]
I do think the second falls more in line with the rest of WebGME's UX, and by hiding the left and right panels you can get a similar effect to method 1 anyway.

**Comment by pmeijer** [comment]
Closed by #1488

**Comment by pmeijer** [comment]
Closed by #1493
