### ISSUE TITLE
Attribute Minimum / Maximum does not persist '0'

### ISSUE THREAD

**Issue by nawgszy** [webgme/webgme#1484]
When creating a new attribute in the meta-model of type 'integer' or 'float', trying to save the 'minimum' or 'maximum' values as 0 will always fail, resulting in no minimum or maximum value being saved.

Steps to re-create:

0. Open Meta Visualizer
1. Add an attribute
2. Select type 'integer' or 'float'
3. Enter a minimum or maximum of 0
4. Press 'Save'
5. Open the attribute and observe that no minimum or maximum is saved

Using WebGME 2.15.1

**Comment by lattmann** [comment]
I would look here for [max](https://github.com/webgme/webgme/blob/faaaed214d0893fa76430df3805ead79d43cddbb/src/client/decorators/MetaDecorator/DiagramDesigner/AttributeDetailsDialog.js#L84) and [min](https://github.com/webgme/webgme/blob/faaaed214d0893fa76430df3805ead79d43cddbb/src/client/decorators/MetaDecorator/DiagramDesigner/AttributeDetailsDialog.js#L87), which will never get set if the `getTypeConvertedValue` function returns with 0.
Cases:
* `NaN`
* `0`
* `cannot parse it as an int or float.`

Reference:
>>>
> 0 ? true : false
false
> NaN ? true : false
false
> Infinity ? true : false
true
> 

Note: by reading the code, if an integer or float [enum](https://github.com/webgme/webgme/blob/faaaed214d0893fa76430df3805ead79d43cddbb/src/client/decorators/MetaDecorator/DiagramDesigner/AttributeDetailsDialog.js#L77) has a 0 in the list that will get ignored as well.

**Comment by kecso** [comment]
First of all, sorry for the late response.
Thank you for noticing!
The issue was known, but as I checked it did not get a separate issue.
Anyhow it is now fixed in release v2.16.0
