### ISSUE TITLE
Dragging from Part Browser fails on any Aspect != CONSTANTS.ASPECT_ALL

### ISSUE THREAD

**Issue by nawgszy** [webgme/webgme#1495]
Steps to recreate:

1. Create a meta where a meta node has an aspect
2. Create a model where there is an instance of that meta node
3. Select that aspect in the Model Editor tabs
4. Try and drag and drop an element, and observe the 'red' background and failure for dropped element to persist

The fix is obvious. In ```webgme/src/client/js/Utils/GMEConcepts.js```, on line 462, there is an expression defining aspectTypes:

```
aspectTypes = parentNode.getAspectMeta(parentId, aspectName);
```

Everywhere else in this file, the definition is simply

```
aspectTypes = parentNode.getAspectMeta(aspectName);
```

Upon applying this change and using debug mode, the Drag and drop behaviour works on any aspect, as expected.

**Comment by pmeijer** [comment]
Thanks for the issue and fix! Also feel free to create PRs
