### ISSUE TITLE
Rewriting tree browser

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#15]
Need for replacing tree browser and unifying context-menus across the UI.

[Requirements - Tree browsers](../wiki/Requirements#tree-browsers)

**Comment by lattmann** [comment]
feature/15 branch was deleted.

A generic [tree browser](http://vu-isis.github.io/isis-ui-components/dist/docs/isis-ui-components-docs.html) implementation is available in [isis-ui-components](https://github.com/vu-isis/isis-ui-components) repository. Use the isis-ui-components repository as a dependency for building domain specific user interfaces and domain specific tree browsers.
