### ISSUE TITLE
Remove project.

### ISSUE THREAD

**Issue by lazydino** [webgme/webgme#1502]
How would one remove a project from webgme.org? Cannot seem to find any way to do it on https://editor.webgme.org/profile/home

**Comment by pmeijer** [comment]
Currently it has to be done using the "editor" from the header toolbar `GME/Manage Projects .../`

Expanding the details will give you the option to remove the project:
![image](https://user-images.githubusercontent.com/6518904/29888846-d0648204-8d87-11e7-99a7-a1e5dd2081cb.png)

Created an issue here:
https://github.com/webgme/user-management-page/issues/70
