### ISSUE TITLE
Show when attributes have mixed values during multiple selection

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1515]
Right now, if you select more than one object, the attribute panel shows attribute values for just the last object selected.  Ideally it would show some indication that the values for this attribute differ between the selected objects, some thing like `---` or a badge of some sort.

**Comment by finger563** [comment]
Would be nice to have the multi-line attributes integrate a similar feature where multi-line attribute editing during multi-selection pops up a diff view to see the differences between the attribute and allow you to edit the resultant attribute value as well.

**Comment by pmeijer** [comment]
@finger563 Can you make a separate issue for your second comment?

**Comment by finger563** [comment]
@pmeijer done :)
