### ISSUE TITLE
Configure a plugin to execute on the server by default

### ISSUE THREAD

**Issue by amoghskulkarni** [webgme/webgme#1552]
Is there a way to configure a plugin to be executed **on the server** by default? I tried to use "Save these settings.." check-box in the dialogue box that opens up when a plugin is executed (i.e. after toggling the "Execute on the server" button), but it didn't work for me.

**Comment by pmeijer** [comment]
In the metadata.json of the plugin, set “disableBrowserExecution” to true.

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/wiki/GME-Plugins#metadatajson

**Comment by amoghskulkarni** [comment]
Thanks a lot! That worked!
