### ISSUE TITLE
[Question] How to re-use the collaborative editing channels 

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#1571]
The multi-line attributes create nice collaborative editing channels which have well-defined semantics for rw to model and include updating and diffing. Is there any example or documentation for re-using these within our own components, e.g. my [code-editor viz](http://github.com/finger563/webgme-codeeditor)?

**Comment by finger563** [comment]
for now I'm just going to look through your [CodeEditor](https://github.com/webgme/webgme/blob/master/src/client/js/Dialogs/CodeEditor/CodeEditorDialog.js) and see if I can re-use some of its code in my own

**Comment by pmeijer** [comment]
The best way to get familiar with ot is to look through [this page](http://operational-transformation.github.io/index.html). That library came with a wrapper for code-mirror so as long as you're using that looking at the code editor in webgme is a good start as well.

If you have a different underlying editor, you would have to make sure to register for the changes and convert them into operation in the OT sense. For that I would look at the (underlying cm-wrapper)[https://github.com/pmeijer/ot.js/blob/master/lib/codemirror-adapter.js] (this is the fork webgme uses).

Another resource is [the OTAttributeEditing plugin](https://github.com/webgme/webgme-engine/blob/master/src/plugin/coreplugins/OTAttributeEditing/OTAttributeEditing.js) which simply appends to a document. Some examples are [here in the tests too](https://github.com/webgme/webgme-engine/blob/master/test/common/storage/storageclasses/watchers_documents.spec.js).

**Comment by finger563** [comment]
one problem i'm running into right now is if I have my viz watching the document (i.e. has an open channel for that node) and the user clicks the property editor `Edit Content...` then the `CodeEditorDialog` throws an error `logger.js:68 Error: Document is already being watched guest+test%master%/M/Z%C++` which crashes the client (i.e. only a refresh will re-enable interactivity)

**Comment by finger563** [comment]
Which is actually a major issue for me, since we usually like to have split panel open with two copies (or more) of my viz and it's not uncommon in that case to be looking at / editing two different attributes of the same node (or even the same attribute viewed in two different places)
