### ISSUE TITLE
Cannot call setFinishTime of undefined

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1577]
If a plugin's callback is invoked with just an error and no result, it will throw an error in the execution of the callback function. The callback should not require multiple args if there is an error and should probably default to the plugin's `self.result`.

**Comment by brollb** [comment]
Wait, this should be made on webgme-engine rather than here. Moved to https://github.com/webgme/webgme-engine/issues/52

**Comment by pmeijer** [comment]
This was fixed in webgme-engine#53
