### ISSUE TITLE
embedded object

### ISSUE THREAD

**Issue by CFAndy** [webgme/webgme#1599]
Dear pal,  
  I'm a new user of webgme and like this tool very much. 
  I have user other GMF based modeling tool which can provide following like DML modeling diagram. So I can view the current level objects together with ones of one level down.  Is there a way to do this in webgme:
![image](https://user-images.githubusercontent.com/8337852/39341061-f0f43198-4a03-11e8-9a59-bdfe49b3a36d.png)
Thanks!
-Andy

**Comment by pmeijer** [comment]
Using the default model-editor there is no support for viewing down the hierarchies. Webgme supports plugging in different visualizers and I'm currently working on a similar view for a different project. Once matured I'm planning on extracting a domain-agnostic version of it and make it available to the public.

In the meanwhile (or if you don't want to wait) you can have a look at @finger563 's Hierarchical FSMs https://www.npmjs.com/package/webgme-hfsm which, of many things, contains a visualizer for displaying multiple levels of containment hierarchy.

To create your own visualizer (or components in general) you can use [webgme-cli](https://github.com/webgme/webgme-cli).

**Comment by CFAndy** [comment]
Thank a lot for valuable comments. Yes. @finger563 provides a great example. It use cytoscape. I'll take a look about that.

**Comment by pmeijer** [comment]
https://github.com/webgme/hierarchical-model-editor

**Comment by finger563** [comment]
Woohoo!
