### ISSUE TITLE
is there a way to know whether the plugin is running on browser or server ?

### ISSUE THREAD

**Issue by ume1087** [webgme/webgme#1607]
In a plugin source code, 
is there a way to know whether the plugin is running on browser or server ?
Because I would like to run  a processing  in the plugin only on server side.

**Comment by finger563** [comment]
You can check

```js
if (typeof WebGMEGlobal !== 'undefined') {
  // the plugin is running in the client
} else {
  // the plugin is running on the server
}
```

**Comment by pmeijer** [comment]
Will is right however I would recommend checking for `window` - which applies regardless of the WebGME UI.
```javascript
if (typeof window !== 'undefined') {
  // the plugin is running in the browser
} else {
  // the plugin is running on the server
}
```

You can always enforce that a plugin should always run on the server by editing the [metadata.json of the plugin](https://github.com/webgme/webgme/wiki/GME-Plugins#metadatajson).

**Comment by ume1087** [comment]
Thanks for the reply.
I will check by WebGMEGlobal or window variable.
