### ISSUE TITLE
How to debug add-ons?

### ISSUE THREAD

**Issue by kevin-bkt** [webgme/webgme#1623]
AddOns are not well documented, and I can find no information on how to debug them.  I've tried debugging the server-side code (app.js) directly using WebStorm, but an error occurs due to the forking of child processes.

`Starting inspector on 127.0.0.1:64269 failed: address already in use`

This appears to be a known and outstanding issue with debugging node.js.

Are there other tools that will work, or is there some other way I can debug my add-on?

**Comment by pmeijer** [comment]
@kevin-bkt I've added a fix in webgme-engine (we explicitly assign a different port for debugger in the spawned processes - however as node evolved I'd forgotten to handle the `--inspect` flag for the add-on).

In the meanwhile (and perhaps a more convenient way in general too) you can use the [addon_handler bin script at](https://github.com/webgme/webgme-engine/blob/master/src/bin/addon_handler.js).

1. Configure the webgme server to send addon-events to a separate server (this matches the default parameters for addon_handler.js.

```
config.addOn.enable = true;
config.addOn.workerUrl = `http://127.0.0.1:${config.server.port + 1}`;
```

2. Run `/node_modules/webgme-engine/src/bin/addon_handler.js` in debug mode (cwd should be the root of your webgme app, same `NODE_ENV` as your server, no additional arguments).


3. To check the options:
```
node /node_modules/webgme-engine/src/bin/addon_handler.js --help
```

Let me know if this helps.

(FYI: don't get burnt on this one https://youtrack.jetbrains.com/issue/WEB-14424).
