### ISSUE TITLE
How to Change Logger Level for Plugin?

### ISSUE THREAD

**Issue by rlhelinski** [webgme/webgme#1626]
Hello, I am writing a plugin for WebGME and wish to see more log messages on the console. I cannot seem to find how to change the logging level while running the plugin. I am running the plugin either directly with:
`node ./node_modules/webgme-engine/src/bin/run_plugin.js ...` 
or through mocha with:
`npm run test`
There is no function `self.logger.setLevel()` as with other loggers.

Once I understand how to do this (there should be many ways), I could help add it to the documentation. Thanks.

**Comment by pmeijer** [comment]
The logger for the bin scripts is configured from your `config/config.**.js` by `config.bin.log.transports`. You can overwrite the array with [an entry like this](https://github.com/webgme/webgme-engine/blob/master/config/config.default.js#L53) (setting level to `'debug'`. If the output is too cluttered, you can add patterns to filter displayed loggers.

**Comment by pmeijer** [comment]
[An example where the server logger is changed for the test configuration](https://github.com/webgme/webgme/blob/master/config/config.test.js#L30)

**Comment by rlhelinski** [comment]
@pmeijer thank you for the info. I was able to change the log level in the mocha tests by adding to the `config.test.js` file. However, I cannot seem to change the level when I call `node ./node_modules/webgme-engine/src/bin/run_plugin.js ...`. I overwrote `config.bin.log.transports` in the `config.default.js` file before the `module.exports = config;` line.

**Comment by pmeijer** [comment]
```
config.bin.log.transports = [{
    transportType: 'Console',
    //patterns: ['gme:server:*', '-gme:server:worker*'],
    // ['gme:server:worker:*'], ['gme:server:*', '-gme:server:worker*']
    options: {
        level: 'debug',
        colorize: true,
        timestamp: true,
        prettyPrint: true,
        handleExceptions: true, // ignored by default when you create the logger
        // see the logger.create function
        depth: 2
    }
}]
```

Works for me. Make sure you use the [right configuration](https://github.com/webgme/webgme/tree/master/config#which-configuration-file-is-being-used). When you use the testFixture in your mocha tests the NODE_ENV is set to `test` from the webgme framework, however when you run run_plugin default will be used unless you explicitly set NODE_ENV somewhere else.

**Comment by rlhelinski** [comment]
OK, I figured out what was going on. The config file I was using was including the `config.default.js` from  `webgme-engine` instead of from my `configs` directory. Thanks for all your help!
