### ISSUE TITLE
Container Deployment Issue - Need mongodb IP

### ISSUE THREAD

**Issue by BigDaddyKahuna** [webgme/webgme#1636]
I'm trying to deploy two containers in Azure, one with webgme, the other with mongodb.   Below is the container definition for webgme:
containers:
      - env:
        - name: GME_ADMIN
          value: admin:admin
        - name: MONGO_PORT_27017_TCP_ADDR
          value: <some dynamically gen'd IP from kubernetes>
        - name: MONGO_PORT_27017_TCP_PORT
          value: "27017"
        image: webgme/webgme-org:2.17.0
        name: webgme
        ports:
        - containerPort: 8001
        volumeMounts:        
        - name: volume        
          mountPath: "dockershare"  

The problem is getting/setting the IP address for the MONGO_PORT_27017_TCP_ADDR environment variable.   While the mongodb container comes up fairly quickly, there is no way to get it's IP address to the webgme container during bootup.

I can  get it to work by first bringing  up the mongodb container, querying it's IP, and adding the IP to the startup .yaml file for webgme.   However, this breaks the paradigm of containers being able to run directly from their images with no further configuration changes.

Is there another mechanism for webgme to connect to mongodb besides using these environment variables?  Can webgme "discover" a mongodb server?   It seems this has to work since I'm using one of your Docker container images.  So, someone has  gotten this working!

**Comment by pmeijer** [comment]
What problem are you trying to solve here? 
If you have your own web-application that you want to deploy you can use a similar setup as for the icore I linked to. Similar boilerplate setup can be generated with the next release of webgme-cli using (`webgme dockerize`). However if you specifically want to deploy the webgme.org image - we can update the image at the new release and provide a compose.yml instead of the "steps".

**Comment by BigDaddyKahuna** [comment]
I've been tasked with setting up an Azure container-based instance of webgme for internal use.  I'm currently using Azure Kubernetes Service which allows Docker containers to be built/managed using Kubernetes, so I can't use docker-compose.  

I'm currently using the environment variables to "tell" webgme the IP and port of the mongodb instance.    I'm wondering if there is another mechanism for webgme to connect to mongodb?   Some way for webgme to be "told" the connection information, or some way to have it discover that information.

**Comment by pmeijer** [comment]
Oh I see. I looked sloppily at your current config and assumed you were using docker-compose (from your question at #1635, btw did that solve your problem there - I took the liberty to close the issue but might have jumped to conclusions). 
Also, it helps a lot if you could decorate your config texts using markdowns `````. That way I can parse it easier.
This is my attempt at indention your config (which is which format btw?):
```
containers:
  - env:
    - name: GME_ADMIN
       value: admin:admin
    - name: MONGO_PORT_27017_TCP_ADDR
       value: <some dynamically gen'd IP from kubernetes>
    - name: MONGO_PORT_27017_TCP_PORT
       value: "27017"
  image: webgme/webgme-org:2.17.0
  name: webgme
  ports:
    - containerPort: 8001
  volumeMounts:
   - name: volume
     mountPath: "dockershare"
```

To answer this question. 
```
Is there another mechanism for webgme to connect to mongodb besides using these environment variables?
```
Yes, all webgme needs is a mongo-uri string (at start up) and in the container you're using the uri string is setup as follows: https://github.com/webgme/webgme.org/blob/master/editor/config/config.docker.js#L50-L61 relying on the now deprecated mongo `link` (which sets the env vars). However you can add whatever logic there and there happens to be a back-door to edit the configuration when the container is running. So if you're bound to that prebuilt image - just add file to your `/dockershare/extraconfigs.js`:
```javascript
function extraConfigs(config) {
  config.mongo.uri = 'mongodb://mongo:27017/webgme';
}
module.exports = extraConfigs;
```

I have no experience with kubernetes I can't give you a complete fix for you issue right now but granted you run the mongo and webgme server under the same network. If you alias the mongo container the configuration above should work `--network-alias mongo`. (Alternatively there might be a way to link containers with kubernetes to.)
