### ISSUE TITLE
Curve control points not moving with both ends of connection 

### ISSUE THREAD

**Issue by gsteinLTU** [webgme/webgme#1642]
This may be sort of a misfeature. If you have a connection set as a Bezier curve and move the nodes it connects to, the curve's control points stay in the same place (in global coordinates). This behavior makes sense when just one end of the connection is moved. However, the control points should probably move if both ends of the connection move. 

As it is now, if you decide to move a bunch of connected nodes (with nice curves between them) to a different position, all the connections will become very warped in a way that you probably didn't intend.

Example:

Before:
![image](https://user-images.githubusercontent.com/7331488/46180395-cff24480-c285-11e8-9b5f-1f360e3806d4.png)

After selecting everything and moving it downward:
![image](https://user-images.githubusercontent.com/7331488/46180424-f0ba9a00-c285-11e8-919e-88535598403b.png)

**Comment by pmeijer** [comment]
This was fixed in v2.32.0. Selecting the two end points together with the connection will move the connection-points as well.
