### ISSUE TITLE
How to set an attribute as calculated?

### ISSUE THREAD

**Issue by gonzalodrobles** [webgme/webgme#1648]
I would like to know how can I describe in "metamodel" that a parent's attribute must be calculated as a sum of childs values

**Comment by pmeijer** [comment]
That's not a feature we support (or intend to support) in the metamodel. This can be solved by using an addon or a plugin.

**Comment by gonzalodrobles** [comment]
Ok thanks.
1- Would you please tell me how can I convert a plugin on AddOn?

**Comment by pmeijer** [comment]
You can generate the boilerplate for an addon with [webgme cli](https://webgme.readthedocs.io/en/latest/getting_started/creating_a_repository.html):
```
webgme new addon --help
```

There no automatic conversion between plugins and addon as they differ in some important aspect (mainly the `main` function and how they store changes). However the APIs are very similar so switching from one to another shouldn't be that hard. 
https://editor.webgme.org/docs/source/AddOnBase.html
https://editor.webgme.org/docs/source/PluginBase.html

**Comment by pmeijer** [comment]
A tip would be to extract the calculation logic to separate module and use it from the addon, but also from any plugin that interprets the model. That way you can ensure that the derived attribute is always correct at the point of interpretation.
