### ISSUE TITLE
feature request: Allow adding operation feature for Nodes

### ISSUE THREAD

**Issue by klpanagi** [webgme/webgme#1649]
Similar to Ecore, it will be really useful to have a way to add operations for Nodes/Classes.

**Comment by kecso** [comment]
If you think about it, EOperation object (and the whole ECore for that matter) is tailored towards domains or languages that are purposefully built for code generation. In those cases, it does make sense to have a specific definition for operations. However, on a meta-programmable level, it would be seen as an overspecification of things. Think about electrical circuits for example. Usually, that domain does not end up in a generated code and does not really have the notion of operations...

If your domain requires such definitions, then just add them (like in case of ECore) and add an attribute that can hold the code itself. It can be done easily with the current feature set. The beauty of WebGME is that you can model on multiple abstraction levels. Creating a small domain that covers something similar to ECore, then extending it with your specific language is totally feasible.

If you had a different scenario in mind than please elaborate and we can discuss such feature.
