### ISSUE TITLE
Link in Plug-in Result Message

### ISSUE THREAD

**Issue by rlhelinski** [webgme/webgme#1650]
I am trying to add a link to another page in a plug-in result message that I have created using `createMessage()`.

I have added HTML tags in the message like `Click <a href="/foo">here</a> to continue`, but when I click on this link in the plug-in result, it changes the URL on my browser's address bar but it does not navigate to the page.

Is there a better way to do this? Is there something I can do to get the browser to navigate away or open in a new window? Thanks

**Comment by pmeijer** [comment]
https://www.w3schools.com/tags/att_a_target.asp

**Comment by pmeijer** [comment]
Try to set the target to `_blank`.

**Comment by rlhelinski** [comment]
@pmeijer Thanks, setting the target to `_blank` worked perfectly.
