### ISSUE TITLE
404 error with jquery.layout.min.js

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#1675]
When not in debug mode, the latest release of webgme does not include `jquery.layout.min.js`. Was it potentially missed when updating jquery semi-recently?

![DeepinScreenshot_select-area_20190321191854](https://user-images.githubusercontent.com/4982789/54833056-94579680-4c7a-11e9-9341-3cf015d08138.png)

**Comment by pmeijer** [comment]
It was added as part of the distribution builds, which minifies the libraries so the minified version wasn't used anymore (by the generic ui that is).
There is a jquery-js path `'jquery-layout'` that loads the bundled (and minified version). It should work for you too. If you're constraint to modify that portion, we can add back the minified version so it doesn't break your code..
