### ISSUE TITLE
installing nodejs/bindings fails

### ISSUE THREAD

**Issue by gkarsai** [webgme/webgme#1700]
Following tutorial -- electrical -circuits repo created. 
When trying to install nodejs/python bindings fails as shown below:
--
C:\Users\gabor\webGME\electrical-circuits>webgme import router BindingDocs webgme-bindings
npm WARN electrical-circuits@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ webgme-bindings@1.2.0
updated 1 package and audited 731 packages in 4.108s

4 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (3 low, 2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:255
        componentPath = utils.getPathContaining(otherConfig[this._webgmeName].basePaths.map(
                                                                              ^

TypeError: Cannot read property 'basePaths' of undefined
    at RouterManager.ComponentManager._getPathFromGME (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:255:79)
    at RouterManager.ComponentManager._getPathFromDependency (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:222:73)
    at RouterManager.ComponentManager._getJsonForConfig (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:184:10)
    at RouterManager._getJsonForConfig (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\RouterManager.js:111:50)
    at RouterManager.ComponentManager._addComponentFromProject (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:164:17)
    at C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\ComponentManager.js:153:18
    at ChildProcess.<anonymous> (C:\Users\gabor\AppData\Roaming\npm\node_modules\webgme-cli\src\utils.js:443:20)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

----

+1: What are those '2 high' vulnerabilities?

**Comment by kecso** [comment]
Could you please check the webgme-cli version on your machine? ('webgme --version')
I have run the tutorial steps and have no issues adding the binding docs.
In the meantime, I will check if we can make the documentation available on the webgme.org so installing the doc router would not be mandatory for individual applications to get documentation.

+1: both are the mongodb DOS vulnerability (which is interesting as this is just the client access that is not available publicly through our implementation...). It should not affect a typical webgme deployment as the mongodb access should not be granted to the outside world (nonetheless, I will check if we can update to a safer version).

**Comment by gkarsai** [comment]
webgme version is v2.8.3
Re: the original error:  The expression otherConfig[this._webgmeName]  seems to return an 'undefined' value. Can the problem be that this is run on a webgme installation that has no project yet?

**Comment by kecso** [comment]
This error should not be related to the projects of the installation. This is more like a library install before the server is even started.
The only thing I can think of is that you might missed the 'npm install webgme-bindings --save' command before importing the router.

Ohhh, I figured out!
It is a misspelling of the component you try to install:
Your first printout shows: 'webgme import router BindingDocs webgme-bindings'
The correct one is: 'webgme import router Binding**s**Docs webgme-bindings'

Please try with that.
I will move this issue to the CLI repository so that we enhance the error printout so that it might give an actual hint on the issue.

**Comment by gkarsai** [comment]
That worked - thanks!
