### ISSUE TITLE
Create instance from code

### ISSUE THREAD

**Issue by arpika99** [webgme/webgme#1713]
Hello,

I know this is not a real issue, but I am new to webgme programming and I would like to ask for a little help.

My goal would be to create an instance from a library and connect it to a node in my project. My problem is that I can create an instance in the project, like dragging the node from the object browser, then clicking the create instance button, but I can not find the method to do it from python code.

All I can do is to create connections on for the childs on one node in the library, like this.

<img width="472" alt="Screenshot 2020-10-01 at 16 31 56" src="https://user-images.githubusercontent.com/55790409/94815895-b8fe0400-0403-11eb-80bd-70af5b3bd4ab.png">

My goal would look like this with same named nodes on the right.

<img width="476" alt="Screenshot 2020-10-01 at 16 35 34" src="https://user-images.githubusercontent.com/55790409/94816389-6cff8f00-0404-11eb-992d-c05ec85ed7c1.png">

I am sorry to disturb in the issues tab but I do not know where to search for answers. 
Thanks in advance.

**Comment by kecso** [comment]
Sorry, but I missed this yesterday.
It's completely fine to ask if you stuck with something, we are here to help!

I hope you closed the issue as you figured out what functions to use, but just to be sure let me sum it up:
You have two options when you look for potential functions, either follow the bindings main setup instructions and build the documentation pages (https://github.com/webgme/bindings) so then the description of all the available functions will become accessible on your own deployment; or follow the regular API description of webgme source code (again, you can find it on your own deployment or [here](http://editor.webgme.org/docs/source/index.html) ). Almost all core function should have its python variant available, so once you have found it, you can start looking or trying it out (the simple route is to switch the camel case into a python function naming...)

For the situation you have described, I would use the create_node function ([js description](https://editor.webgme.org/docs/source/Core.html#createNode__anchor)). Just make sure that you have the information of the intended container and base of the node to be created (the base will be the library in your case).

Hope this helps!

Tamas

**Comment by arpika99** [comment]
Tisztelt Tamás,

Köszönöm szépen hogy válaszolt a github-on feltett kérdésemre.

Sikerült rájönnöm másnap a probléma megoldására, ezért tettem át a
megoldott problémák közé. A python bindingokat is megtaláltam és
folyamatosan használom, de mindig valami apróság, ami miatt elakadok amikre
csak hosszú gondolkodás után jövök rá, mint az előző problémára.

Most egy másik problémába ütköztem, ahol van egy set-em amire bekötöttem
membereket a libraryból. Majd az egyik bekötött memberből létrehoztam egy
példányt és lekértem annak a parent-jét, mert csak rajta keresztül tudom
elérni a set-et. Az a problémám, hogy hiába kapom meg azt, hogy a parent
node-hoz tartozik egy set (ennek neve DeviceMembers), mert nem találok
olyan függvényt, amely megmondaná, hogy ez a node, ezzel a névvel
rendelkező set-hez tartozik, amelynek a parent-je SmallEquipments.
Csatoltam egy képet is a könnyebb magyarázatért.

Ha esetleg lesz egy kis ideje kérem segítsen. Remélem nem okozok ezzel
problémát

Előre köszönöm,
Adorjáni Árpád

Tamas Kecskes <notifications@github.com> ezt írta (időpont: 2020. okt. 2.,
P, 15:49):

**Comment by arpika99** [comment]
Elnézést kérek. Gmail-ról írtam az előző levelemet, ezért a csatolmány nem továbbítódott.
<img width="594" alt="Screenshot 2020-10-09 at 17 22 21" src="https://user-images.githubusercontent.com/55790409/95611546-a40c1b00-0a6a-11eb-8fe5-280d426f5c2d.png">

Az is_member_of függvénnyel, a CMBSD.EC-XS-SP noderól kérdezve megkapom a rózsaszínnel jelölt kapcsolatot a "DeviceMembers"-t, de hogyan kaphatom meg a másik oldalon levő node-ot?

**Comment by kecso** [comment]
Az 'is_member_of' függvény egy struktúrált objektumot ad vissza, node-id hoz rendeli a halmaz neveket. Ez azt jelenti, hogy amint megvan a keresett halmaz, úgy az ahhoz tartozó bejegyzés kulcsa lesz a halmaz tulajdonosa (SmallEquipment ebben az esetben).
Ezután load_by_path függvénnyel (első paraméter a gyökér elem, a második pedig a kinyert azonosító) lehet magát az objektumot lekérni.

**Comment by arpika99** [comment]
Köszönöm szépen a segítséget. Sikerült megvalósítani a feladatot.
Elnézést kérek ha zavartam. 

Tisztelettel,
Adorjáni Árpád

**Comment by kecso** [comment]
Semmi gond! Örülök, hogy sikerült megoldani a problémát!
Máskor is szívesen segítünk!

Tamás
