### ISSUE TITLE
GMENode information not consistent across visualizers/panels

### ISSUE THREAD

**Issue by arora-r** [webgme/webgme#1721]
If I use `WebGMEGlobal.Client.getNode('ACTIVENODE')` in one Visualizer (Panel A), I get the expected nodes within the _state inside the GMENode object. However, if I go to a different visualizer page (Panel B) then run the same command I'll have different values inside the GMENode.

Essentially what Im trying to accomplish through code is:
- From Panel B delete some nodes from the root object
- Then from Panel B create some nodes on the root object

Right now I can delete the nodes from Panel B only if I directly switch panels from A to B, but when I run the creation, the nodes wont load into the GMENode until I switch to the Panel A page (i.e. if I run the delete command, then the create command, then the delete command again, the newly created nodes wont delete).

Also, if I go from another panel (Panel C) to Panel B then try deleting the nodes, it does not work because not all the nodes are retrieved (The children are not found).

Example steps to see the idea:
1. Go into the model editor panel (in root)
2. Drag & drop an object to the canvas
3. Go into the object
4. Add multiple nodes (state nodes)
5. Go into the browser console and run: `WebGMEGlobal.Client.getNode('$THE_OBJECT_ID')` ($THE_OBJECT_ID should be something like /Q) and take note of the nodes inside the _state attribute
6. Switch visualizers to 2 different visualizers
7. Run step 5 again and view the nodes attribute again (note should be missing the child nodes of the object)

Is there a way to directly add or delete children on a GMENode?

**Comment by kecso** [comment]
First and foremost, there is no such thing as Panel A's nodes. Your project has nodes, and through the client, any panel/visualization code could access them. There is a territory mechanism, which is responsible for sending change events to different panels. There it is important that the panel defined the set of nodes that it cares about. On the other hand when it comes to accessing nodes, all panels has the same capabilities.

So, to help you better achieving your goal:
- Could you send the webgme project where you want to create 'contracts' and 'state nodes'?
-  Your description of step 5 already suggests that you are trying to depend on values you should not (_variables are not public in general and therefore you should not draw any conclusion on their value) 
- In your description, step 6 is very important as it might change the context as well
- GMENode object itself is not something that you should take and interpret as an object. It is class that you can call functions on, and interpret the returned values, nothing more.

To address you immediate question, no, the GMENode is only there for inquiries. You can only change the model via functions of the client API or using other methods that use the core API.

Additionally, it would also help if you could describe your end goal on where you would like to use 'programmatic'  node creation and removal as I suspect it is not the browser's console (as it was not intended to be done that way...)

**Comment by arora-r** [comment]
Ah right sorry, I had explained the issue wrong (mentioning the "nodes of a Panel", I meant to say be nodes of a project, cascading into the contract/object).

The real goal is to create a model through a button on a separate panel. I.e. from a newly created panel having a button to delete the current nodes in the model editor canvas and then creating a new set of nodes.

This is the piece of code Im using right now:

```       
var del = gmeClient.getNode(initialState.activeNode).getChildrenIds(); // Get nodes in the current contract
gmeClient.startTransaction();

// deletion
gmeClient.deleteNodes(del); // Delete the nodes in the contract

// Creation
var state =  gmeClient.createNode({parentId: initialState.activeNode, baseId: '/m/9'}); // Create a state node

["name1", "name2"].forEach(fn => {

    var transition = gmeClient.createNode({ parentId: initialState.activeNode, baseId: '/m/A' }); // Create a transition node

    gmeClient.setAttribute(transition, 'name', fn);
    gmeClient.setAttribute(transition, 'statements', fn);
    gmeClient.setAttribute(transition, 'input', fn);
    gmeClient.setAttribute(transition, 'output', fn);
    gmeClient.setAttribute(transition, 'tags', fn);
    gmeClient.setPointer(transition, 'src', state);
    gmeClient.setPointer(transition, 'dst', state);
    
});
gmeClient.completeTransaction();
```
Where
`gmeClient={window.WebGMEGlobal.WebGMEReactPanels[VISUALIZER_INSTANCE_ID].client}`
`initialState={window.WebGMEGlobal.WebGMEReactPanels[VISUALIZER_INSTANCE_ID].initialState}`

I guess the real issue is mainly just with my understanding of webgme's api with how to about defining/using `gmeClient` and `initialState`. I'm guessing the `Territory` mechanism would probably be the better approach (I'll try looking more into this for now)

**Comment by kecso** [comment]
It is still interesting how you intend to execute this code?
I ask as the standard and default way is to create your own visualizer/panel.
Try to check this tutorial: https://webgme.readthedocs.io/en/latest/
It is probably the first time I see someone trying to access these APIs through window global variables. (and to get them through reactpanels?)
Could you point me to the source of your development (I mean we have some react based work, maybe that is why your code seems odd as we are not heavily using those - though they should still work)?

for a quick response:
- gmeClient = WebGMEGlobal.Client
- activeNode = WebGMEGlobal.State.getActiveObject()

(it is quite hard to tell what those internal variables you are trying to use of visualization implementation really have as we have no standard on those or way to enforce their content...)

**Comment by arora-r** [comment]
The purpose is to have some button generate a model in the model editor panel (the base active node) based on some code defined on the panel with the button. The issue lies with how Im using createNode() and deleteNode().

`gmeClient.getNode(initialState.activeNode).getChildrenIds()` is always able to find the children of the active node but running `gmeClient.deleteNode()` does not always seem to find the created nodes in the active node. 

I've created [this repo](https://github.com/arora-r/verimove-base) and given you access to give you a better idea. If you start that up. And create a project with the defined default seed, navigate into the "contracts" object on the model editor, then go into `auction`, switch over to the `ModelEditor` from the visualizer's panel, and clicking the "Generate FSM" button will trigger the code from earlier.

**Comment by arora-r** [comment]
Sorry for the spam but I have another specific question. Is there any way to switch visualizer panels programatically? For example at the end of that button method above, switching the active panel to a different one. I tried using the Panel Manager (WebGMEGlobal.PanelManager.setActivePanel('ModelEditor')) and setting the active panel to a different one but this wouldn't be enough and causes the error below:

```
"clientState": {
    "connection": "CONNECTED",
    "renewingToken": false,
    "exception": {
      "message": "activePanel.destroy is not a function",
      "stack": "TypeError: activePanel.destroy is not a function\n    at VisualizerPanel._setActiveVisualizer (http://localhost:8888/dist/webgme.2.42.0.dist.build.js:59319:29)\n    at HTMLLIElement.<anonymous> (http://localhost:8888/dist/webgme.2.42.0.dist.build.js:59260:18)\n    at HTMLDivElement.dispatch (http://localhost:8888/dist/webgme.2.42.0.lib.build.js:2:18648)\n    at HTMLDivElement.g.handle (http://localhost:8888/dist/webgme.2.42.0.lib.build.js:2:16657)"
    }
```

**Comment by kecso** [comment]
I suspect that both errors come from an incomplete or non-standard implementation of visualizers. If I have time, I will try to recreate in your repository to see, what the source of these things might be.
In the meantime a few tips:
- try to load the /debug.html, as that uses the source files instead of the compiled module, which makes debugging a bit easier
- for state manipulations, check out https://github.com/webgme/webgme/blob/master/src/client/js/Utils/StateManager.js. It allows you to set visualizer, selection, context, and such. Keep in mind that some changes might require more attention as there are implemented automations (for example, changing the activenode/context might also changes the visualization...)

Hope this helps!

**Comment by arora-r** [comment]
Awesome, `WebGMEGlobal.State.registerActiveVisualizer('')` solved my issue of switching panels. Its kind of a round-a-bout method of avoiding the other issues from above too.

Thank you so much for your quick responses and help, I really appreciate it!
