### ISSUE TITLE
The usage of the API:src/server/api/index.js

### ISSUE THREAD

**Issue by Ayman-Meidan** [webgme/webgme#1735]
Hell,
I need to extract the model data using API, I tried the available endPoints in the API:
https://github.com/webgme/webgme-engine/blob/fc8bc502fc7ce2e5caf6d2cfbda851ec31802eea/src/server/api/index.js

but I do not find any endpoint that can access the project and retrieve the metamodel data.
For example the API: /api/projects/guest/FSM/branches/master/export

Retrieve a webgmex file, but I could not extract data from it.

I see it is possible via plugin, but I need to do it using API.

Also, I need to know if it is possible to add/modify nodes using the above-mentioned API or another available API.

Best regards.

**Comment by kecso** [comment]
Hello,

WebGME stores uninterpreted data and therefore does not provide API for data components directly.
Usually, as these exchange formats are highly domain dependent, so we suggest creating a server side endpoint that can handle these additional REST API calls ([rest router](https://github.com/webgme/webgme/wiki/REST-Routers)). 
You can also combine the power of the plugin API and the REST routers if you define calls that in turn initiate plugins that extract the data in the format you need (or make modification to the model).

Let us know if you need further assistance!

br,
Tamas

**Comment by Ayman-Meidan** [comment]
Thanks a lot for your quick reply,
I will study these suggestions and get back to you.

I already tried to run the my plugin via the API endPoints, but I get an error message... I don't know what's wrong:

EndPoints used:
POST: http://localhost:8888/api/plugins/MetaExporter/run?projectId=guest+FSM&branchName=master
POST:http://localhost:8888/api/plugins/MetaExporter/execute?projectId=guest+FSM&branchName=master

1) In the execute case, I get this response:
{
    "resultId": "620f2746-d90b-588c-76ce-2d432291d30a"
}

but I used this (http://localhost:8888//blob/view/620f2746-d90b-588c-76ce-2d432291d30a) to get the details but I got: "Not Found"

2) The /run endPoint give me this error message in the response:
           "message": "Invalid argument, data.projectId is not a string.",
            "severity": "error"

The complete response is:

{
    "success": false,
    "messages": [
        {
            "commitHash": "",
            "activeNode": {
                "name": "",
                "id": ""
            },
            "message": "Invalid argument, data.projectId is not a string.",
            "severity": "error"
        }
    ],
    "artifacts": [],
    "pluginName": "MetaExporter",
    "startTime": "2021-08-03T15:52:38.839Z",
    "finishTime": "2021-08-03T15:52:38.839Z",
    "error": "Invalid argument, data.projectId is not a string.",
    "projectId": "N/A",
    "pluginId": "MetaExporter",
    "commits": []
}

Your collaboration is appreciated.
BR
/Aym

**Comment by Ayman-Meidan** [comment]
Hello,
Any idea about this error, in the API request I pass the project ID as a parameter, but I get the error: Invalid argument, data.projectId is not a string.

thanks in advance for your cooperation
Best regards.

**Comment by Ayman-Meidan** [comment]
I am still facing the same error, any help?

The /run endPoint gives me this error message in the response:
"message": "Invalid argument, data.projectId is not a string.",
"severity": "error"

**Comment by kecso** [comment]
Sorry for the late response:
https://editor.webgme.org/developer/api#plugins__pluginId__run_post
you need to fill out at least these two parameters in your post request, otherwise the system will not be able to execute your plugin....

**Comment by Ayman-Meidan** [comment]
Thanks for your response.

I am using PostMan to send this post request:
http://localhost:8888/api/plugins/aymApiTestPlugin/run?projectId=guest+FSM_Septiembre&branchName=master
This used plugin is the standard plugin template (change the name of the active node)

**# In case using run API,** I get this error in the PostMAn response: 

"error": "Invalid argument, data.projectId is not a string.",
    "projectId": "N/A",
    "pluginId": "aymApiTestPlugin",
    "commits": []
As you see I include the projectID and the branchName in the request, but the API returns this error.

**# in case using execute API:**
http://localhost:8888/api/plugins/aymApiTestPlugin/execute?projectId=guest+FSM_Septiembre&branchName=master

- in the PostMan I get : "resultId": "9c131196-ebf7-198c-2ff3-653d77755350"
- But in the log I get the error:

(node:1828) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
2021-09-21T07:34:56.847Z - error: [gme:server:worker:simpleworker:pid_1828:WorkerFunctions] plugin [aymApiTestPlugin] failed with error
{
  message: 'Invalid argument, data.projectId is not a string.',
  stack: 'Error: Invalid argument, data.projectId is not a string.\n' +
    '    at C:\\webgme-Repository\\node_modules\\webgme-engine\\src\\server\\worker\\workerrequests.js:264:27\n' +
    '    at _fulfilled (C:\\webgme-Repository\\node_modules\\q\\q.js:854:54)\n' +
    '    at C:\\webgme-Repository\\node_modules\\q\\q.js:883:30\n' +
    '    at Promise.promise.promiseDispatch (C:\\webgme-Repository\\node_modules\\q\\q.js:816:13)\n' +
    '    at C:\\webgme-Repository\\node_modules\\q\\q.js:624:44\n' +
    '    at runSingle (C:\\webgme-Repository\\node_modules\\q\\q.js:137:13)\n' +
    '    at flush (C:\\webgme-Repository\\node_modules\\q\\q.js:125:13)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:77:11)'
}
(node:4420) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

2021-09-21T07:35:56.882Z - warn: [gme:server:standalone:api] Plugin result timed out: 60000[ms] 9c131196-ebf7-198c-2ff3-653d77755350

Looking forward to your response.
BR

**Comment by Ayman-Meidan** [comment]
Thanks a lot for your support, it is working now.
We are very appreciated.
BR
