### ISSUE TITLE
Nginx proxy path prefix

### ISSUE THREAD

**Issue by iamfoolberg** [webgme/webgme#1757]
I followed the instructions in https://github.com/webgme/webgme.org/blob/master/aws/ubuntu16.04/nginx.conf,
but when the location is "/wgg/" instead of "/", the socket.io does not work:
1.the path is still http://the.ip.addr/socket.io/socket.io.js, should be http://the.ip.addr/wgg/socket.io/socket.io.js
2.the connection dose not work, when i added a location /socket.io/ --> http://the.ip.addr:8001/socket.io/socket.io.js in nginx

How can i use nginx to forward the webgme  like:
```
           location /wgg/ {
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $http_host;
                    proxy_set_header X-NginX-Proxy true;

                    proxy_pass http://the.ip.addr:8001;
                    proxy_redirect off;

                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection $connection_upgrade;
            }
```

**Comment by pmeijer** [comment]
There's an extra header that needs to be passed down to the webgme server if you want to mount the app at a non-root location. You can see an example here:
https://github.com/webgme/webgme/wiki/Routing

**Comment by pmeijer** [comment]
Not sure if this is relevant anymore since it's been 3 months...
