### ISSUE TITLE
webgme 2.45.0 python plugin does not run

### ISSUE THREAD

**Issue by mnag1124** [webgme/webgme#1784]
Python based plugins do not run on webgme 2.45.0. Reverted back to 2.44.0 where the plugins run fine.

**Comment by pmeijer** [comment]
Plugins in general can't be executed on the server.

This fails if cookies is undefined or empty.
https://github.com/webgme/webgme-engine/blob/master/src/server/storage/websocket.js#L894
The checks here are wrong, should be "object".
https://github.com/webgme/webgme-engine/blob/master/src/server/worker/workerrequests.js#L194
