### ISSUE TITLE
MetaEditor should strip away the namespace when viewing a meta model from a library

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#1792]
In this example `taxonomy` shouldn't be displayed - which makes the view look like it did when it was created and much more readable.

![image](https://github.com/webgme/webgme/assets/6518904/4c6c54fe-04f3-4964-9d21-55475db383f9)

**Comment by kecso** [comment]
While I fully agree, I would add that stripping the namespace coudl lead to confusion if the user is not fully aware of the context.
So either canging the background 'META' to 'Meta.taxonomy' or something eaqually visible note would also be needed for this change (as the dropdown is kinda small for this purpose and out of the way).

**Comment by pmeijer** [comment]
I hear you and agree, with the only difference of displaying it as `taxonomy.Meta` and `taxonomy.Content Types` etc.
