### ISSUE TITLE
Update configuration structure.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#205]
var config = {

    server: {
        port: 8888,
        sessionCookieId: 'webgmeSid',
        sessionCookieSecret: 'meWebGMEez',
        https: {
            enable: false,
            certificateFile: './src/bin/proba-cert.pem',
            keyFile: './src/bin/proba-key.pem'
        }
    },

    client: {
        appDir: './src/client',
        // Used in client/WebGME.js to load initial project.
        defaultProject: {
            name: null,
            branch: null,
            node: null
        }
    },

    mongo: {
        uri: 'mongodb://127.0.0.1:27017/multi',
        options: {
            w: 1,
            'native-parser': true,
            auto_reconnect: true,
            poolSize: 20,
            socketOptions: {keepAlive: 1}
        }
    },

    socketIO: {
        reconnect: false,
        'connect timeout': 10,
        'reconnection delay': 1,
        'force new connection': true,
        transports: ['websocket']
    },

    log: {
        debug: false,
        level: 1, // 5 = ALL, 4 = DEBUG, 3 = INFO, 2 = WARNING, 1 = ERROR, 0 = OFF
        file: 'server.log'
    },

    authentication: {
        enable: false,
        salts: 10,
        allowGuests: false,
        logOutUrl: '/',
        guestAccount: 'anonymous'
    },

    blob: {
        type: 'FS', //'FS', 'S3'
        fsDir: './blob-local-storage',
        s3: {}
    },

    executor: {
        enable: false,
        nonce: null
    },

    plugin: {
        allowServerExecution: false,
        basePaths: ['./src/plugin/coreplugins'],
    },

    rest: {
        secure: false,
        components: {}
    },

    addOn: {
        enable: true,
        basePaths: ['./src/addon/core']
    },

    visualization: {
        decoratorPaths: ['./src/client/decorators'],
        visualizerDescriptors: ['./src/client/js/Visualizers.json']
    },

    storage: {
        keyType: 'plainSHA1', // 'rand160Bits', 'ZSSHA', 'plainSHA1',
        timeout: 10000,
        failSafe: 'memory',
        failSafeFrequency: 10000
    },

    requirejsPaths: {}
}

**Comment by pmeijer** [comment]
I suggest the default port to be 8888 rather than 80 since 80 isn't available on windows.

**Comment by pmeijer** [comment]
Perhaps secureREST, httpsecure, sessioncookieid, sessioncookiesecret could be grouped. And authentication and guest might be related too.

**Comment by ksmyth** [comment]
I'd suggest consistency in capitalization. 
sessioncookieid => sessionCookieId
decoratorpaths => decoratorPaths
also, logFile, logLevel, sessionCookieSecret, httpSecure, mongoUri (or mongoURI)

**Comment by ksmyth** [comment]
Also, are all configuration keys listed? Or are we missing some?

**Comment by ksmyth** [comment]
"guest" really means "allow anonymous access". It could stand to be renamed

**Comment by lattmann** [comment]
I suggest to have sub keys per features:
```
auth: {
// auth specific settings
}

webserver: {
// webserver specific settings
}

rest: {
// rest specific settings
}

ui: {
// decorators + visualizers
}

plugin: {
// plugin specific configs
}

requirejs: {
    path: {}
}
```

**Comment by brollb** [comment]
I think "autorecconnect" should be "autoreconnect"

**Comment by pmeijer** [comment]
Guys based on your comments I've updated the suggested config. (Some of the options aren't available yet.)
