### ISSUE TITLE
Change of attribute type of base do not propagate correctly

### ISSUE THREAD

**Issue by kecso** [webgme/webgme#249]
Error scenario:
1. create an empty project
2. add an attribute to FCO ('something', type = 'asset')
3. create an FCO_instance (right in the META editor)
4. create an attribute for FCO_instance('another', type = 'integer')
4. change the type of something to 'float'
5. check the property editor of FCO_instance (by selecting it)

-> in the property editor, the something will still be visualized as it were an asset...

**Comment by pmeijer** [comment]
This works if asset is replaced with a boolean.
