### ISSUE TITLE
Client sends message out-of-order

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#274]
`set LOG_WEBGME_TIMING=1` and move a model on the canvas:

    yWteU9YRr-3bkK8MAAAA 49 insertObjects 3 recvd
    yWteU9YRr-3bkK8MAAAA 49 insertObjects 3 47 null
    yWteU9YRr-3bkK8MAAAA 50 fsyncDatabase recvd
    yWteU9YRr-3bkK8MAAAA 50 fsyncDatabase 0 undefined
    yWteU9YRr-3bkK8MAAAA 51 insertObjects 1 recvd
    yWteU9YRr-3bkK8MAAAA 52 setBranchHash master: #85768552453eb741818b736f0303534d9194b85f -> #253691aaadaaad1419fb261b68f318c3bd693dec recvd

The fsyncDatabase call should come after all the insertObjects. The way it is now, there is a possible race that setBranchHash will complete before the inserObjects 1 (this is the commit object), and collaborating clients' calls to getObject(commit obj) will fail.

The commit object should be sent in the previous insertObjects batch.

**Comment by pmeijer** [comment]
This is resolved with #370 since these are sent in one commit-package.
