### ISSUE TITLE
Extend project protocol to load objects smarter

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#278]
When someone else changes a project, the webgme client takes lots of round trips to load the new objects. This is slow when communication to the server is over the Internet.

![webgme delay](https://cloud.githubusercontent.com/assets/1047813/6901461/e553a62c-d6d2-11e4-922b-7498a76022f7.png)

This image is a capture of communication from Nashville to a webgme server to GCE's US central 1 (theorized to be Oklahoma). It shows the getBranchHash reply and 6 loadObject request/reply pairs. It takes over 1 second to load this commit.

These loadObjects should be optimized. For instance, we know that the very first the client will do after receiving a getBranchHash reply is to load the commit object. Why doesn't the server send it with the getBranchHash reply?

Optimizing the loadObjects for the graph nodes is harder, since the server must know which objects are loaded in the client. But I think it should be done, as it would be a big win for performance.

**Comment by ksmyth** [comment]
Btw, this screenshot is from the Socket.IO Wireshark dissector I wrote: https://github.com/ksmyth/wireshark-socket.io

**Comment by ksmyth** [comment]
Also of note is the delay between receiving the loadObjects reply and sending another loadObjects request. I think this is from `storage/client.js`'s `loadBucketTimer = setTimeout(function(){` ...

**Comment by pmeijer** [comment]
This is partially resolved with #370. The commit object and root node are packaged with the HASH_UPDATED event-data.

**Comment by pmeijer** [comment]
See #474 too.
