### ISSUE TITLE
Double click on a connection adds custom routing point. Autorouter (ConnectionRouteManager3) fails to draw the connection

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#288]
When a connection is double clicked, it is removed from current sheet while this connection stays visible in the object browser. In addition, the project becomes unnavigable. The visualization sheet of models are not updated when 'go to parent' clicked or any object is double clicked.

```Uncaught TypeError: Cannot read property 'attr' of undefinedConnection.js:694 Connection._unHighlightPathConnection.js:676 Connection.onDeselectSelectionManager.js:290 SelectionManager._clearSelectionSelectionManager.js:397 SelectionManager._setSelectionSelectionManager.js:55 _diagramDesigner.onItemMouseDownDiagramDesignerWidget.Mouse.js:31 (anonymous function)jquery-2.1.0.js:4371 jQuery.event.dispatchjquery-2.1.0.js:4057 elemData.handle```

**Comment by kecso** [comment]
The connection is not removed. Unfortunately, it seems that adding a custom path point (that is what double-click does normally) crashes the autorouter.
AutoRouter.remove failed with error: TypeError: Cannot read property 'removePoint' of null:8888/js/logger.js:66 log.error
2:8888/js/Widgets/DiagramDesigner/Connection.js:1349 Uncaught TypeError: Cannot read property 'getTotalLength' of undefined
2:8888/js/logger.js:66 AutoRouter.remove failed with error: TypeError: Cannot read property 'removePoint' of null:8888/js/logger.js:66 log.error
:8888/js/Widgets/DiagramDesigner/Connection.js:694 Uncaught TypeError: Cannot read property 'attr' of undefined
2:8888/js/logger.js:66 AutoRouter.remove failed with error: TypeError: Cannot read property 'removePoint' of null:8888/js/logger.js:66 log.error
logger.js:66 AutoRouter.clear failed with error: TypeError: Cannot read property 'removePoint' of null


As a workaround solution, you can switch to other connection modes, remove the custom points and switch back to autorouter. Or if you need the custom path points then please use different connection modes for the time being.

**Comment by lattmann** [comment]
To reproduce:
1) Create a new model with a connection
2) Select `ConnectionRouteManager3`, a.k.a. autorouter
3) Double click on the connection __connection disappears from the UI, but NOT deleted__
4) Switch to route manager 2 it will show the connection

The correct stack trace:
```enabledlogger.js:64 log.errorConnectionRouteManager3.ActionApplier.js:171 AutoRouterActionApplier._invokeAutoRouterMethodConnectionRouteManager3.js:292 ConnectionRouteManager3.deleteItemConnectionRouteManager3.js:168 ConnectionRouteManager3._refreshConnDataConnectionRouteManager3.js:115 ConnectionRouteManager3.redrawConnectionsDiagramDesignerWidget.js:1384 DiagramDesignerWidget._redrawConnectionsDiagramDesignerWidget.js:707 DiagramDesignerWidget._refreshScreenDiagramDesignerWidget.js:613 DiagramDesignerWidget._tryRefreshScreenDiagramDesignerWidget.js:583 DiagramDesignerWidget.endUpdateModelEditorControl.js:452 ModelEditorControl._dispatchEventsModelEditorControl.js:278 (anonymous function)DecoratorManager.js:56 DecoratorManager.download.processDecoratorsDecoratorManager.js:52 (anonymous function)DecoratorManager.js:163 (anonymous function)```

@kecso's stack trace shows probably when you double click on the connection and `ConnectionRouteManager3` is enabled.
