### ISSUE TITLE
New branch isn't visible before reloading the page

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#318]
When a new branch is created from a commit in toolbar >> [[project name]] >> show history, the toolbar doesn't show the newly created branches in toolbar >> [[project name]] >> recent branches. When the page is reloaded, the recent branches list is updated.

**Comment by hakantunc** [comment]
In addition, when a branch is deleted from the recent branches list or from the show history, it still appears in the list until the page is reloaded.

**Comment by lattmann** [comment]
Same for projects. Deleted projects still appear in the list, until we reload the page.

**Comment by hakantunc** [comment]
New branches still do not appear in the dropdown menu of the _project name_ in the toolbar. They do appear in the dropdown menu of 'GME' through > 'Recent Projects' > 'Recent Branches' though.
