### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#344]
Says: Can not connect to DB.

**Comment by nabana** [comment]
![image](https://cloud.githubusercontent.com/assets/949040/7254250/72975aac-e807-11e4-99ba-fd2fe7cc9880.png)

**Comment by lattmann** [comment]
> err.stack
< "callbackTimeout@http://editor.dev.webgme.org/common/storage/client.js:82:29"
> err.message
< "no valid response arrived in time"

**Comment by lattmann** [comment]
Changing socket-io client transport from `websockets` to `polling` has no issue.
