### ISSUE TITLE
Leftover "debugger;" statement 

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#345]
![image](https://cloud.githubusercontent.com/assets/949040/7255394/a64f66f8-e80e-11e4-80ba-e689ddabb4b7.png)

**Comment by lattmann** [comment]
Where is this?
I cannot see it on the master branch nor in the latest release...
https://github.com/webgme/webgme/blob/master/src/common/util/assert.js
https://github.com/webgme/webgme/blob/v0.9.2/src/common/util/assert.js

**Comment by lattmann** [comment]
Found it d03f0a5137dfe7bb84ca8820c9f43eaac514200b and assigned the issue to @ksmyth
