### ISSUE TITLE
Multiple sources of a connection

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#366]
When a connection has more than one source, ModelEditorControl tries to access negative index (-2) of an array.

https://github.com/webgme/webgme/blob/master/src/client/js/Panels/ModelEditor/ModelEditorControl.js#L601:L603

```l = 0``` can be added after line 602, but I think two _for_ loops will be safer.
```javascript
for (k = sources.length - 1; k >= 0; k--) {
  for (l = destinations.length - 1; l >= 0; l--) {
    //
  }
}
```

**Comment by lattmann** [comment]
How can I reproduce this? I am ok with your fix, but would like to make sure I can test it.
