### ISSUE TITLE
Client does not reconnect: enable socket io automatic reconnection in default config

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#368]
1. Open any model
2. restart the server, or disconnect from wifi, or use tcpview to kill the connection, or unplug the router, or otherwise have the websocket connection terminated
3. The client shows Disconnected and never reconnects

**Comment by lattmann** [comment]
https://github.com/webgme/webgme/blob/master/config/config.default.js#L160 - set the reconnect parameter to true.

**Comment by ksmyth** [comment]
I didn't know about that parameter. I think it should default to true.

With reconnect=true, it still doesn't work

**Comment by lattmann** [comment]
That was just my guess what should be changed. One of us will look into this.
