### ISSUE TITLE
Autorouter fails

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#372]
In **Meta** view, if an object is dragged to the left border, autorouter doesn't draw many of the connections and throws the following error:
```
AutoRouter.routeSync failed with error: Error: AREdgeList.insert: CONSTANTS.ED_MINCOORD <= y && y <= CONSTANTS.ED_MAXCOORD FAILED (y is -3)logger.js:66
log.errorAutoRouter.ActionApplier.js:178 
AutoRouterActionApplier._invokeAutoRouterMethodConnectionRouteManager3.js:140 
ConnectionRouteManager3.redrawConnectionsDiagramDesignerWidget.js:1439 
DiagramDesignerWidget._redrawConnectionsDiagramDesignerWidget.js:734 
DiagramDesignerWidget._refreshScreenDiagramDesignerWidget.js:636 
DiagramDesignerWidget._tryRefreshScreenDiagramDesignerWidget.js:606 
DiagramDesignerWidget.endUpdateMetaEditorControl.js:148 
MetaEditorControl._eventCallbackMetaEditorControl.js:1848 (anonymous function)index.js:970 
userEventsindex.js:1208 finalEventsindex.js:1224 (anonymous function)VM1323 tasync.js:534 
func.tasync_unwrapedindex.js:1189 (anonymous function)VM1323 tasync.js:534 
func.tasync_unwrapedindex.js:1158 loadRootindex.js:1219 loadingindex.js:113 (anonymous 
function)VM1349 failsafe.js:424 setBranchHashindex.js:110 saveRootindex.js:206 
completeTransactionMetaEditorControl.DiagramDesignerWidgetEventHandlers.js:222 (anonymous function)
```

**Comment by brollb** [comment]
The assert that is failing is checking that the connection is on the grid. Are you using custom port/box decorators?

I suspect that the box is placed on the canvas/grid but then a connected port is out of view and causes the connected path to be out of bounds (in this case, the edge is at x=-3).

**Comment by hakantunc** [comment]
I think this issue is fixed or somehow not a problem in the master branch. I can reproduce this error in 'v.0.10.2' but not in the current master branch.

I don't think it is related to custom decorators since it happens in Meta view. I'm closing this since it's not reproduced in the master branch.
