### ISSUE TITLE
Context menu throws an error

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#373]
When the context menu is clicked after an object selected, WebGME throws the following error:

![screenshot from 2015-05-28 16 16 36](https://cloud.githubusercontent.com/assets/5684384/7871350/f38d8f36-0554-11e5-824c-b1b11b3eee1d.png)

**Comment by lattmann** [comment]
How to reproduce this?

**Comment by hakantunc** [comment]
I couldn't reproduce it with the latest beta.
