### ISSUE TITLE
Object browser auto scroll, when navigating with the keyboard

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#408]
When traversing the object browser with the keyboard, the selected/active object should be visible.

**Comment by pmeijer** [comment]
Can you add a snippet?

**Comment by hakantunc** [comment]
**Timer1** is selected in the object browser. When I press the **down** button twice, the object below **Timer2** is selected but the object browser doesn't scroll down automatically to keep the selected object visible.

![1](https://cloud.githubusercontent.com/assets/5684384/8195004/04319036-1445-11e5-9663-87c8299d0b96.png)
![2](https://cloud.githubusercontent.com/assets/5684384/8195005/04352534-1445-11e5-8e76-19c4354bd822.png)

**Comment by lattmann** [comment]
Did it ever scroll automatically?

**Comment by hakantunc** [comment]
Nope
