### ISSUE TITLE
Superagent not found

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#409]
WebGME does not load unless I change the filename form 1.2.0 to 1.1.0 at src/client/lib/superagent/superagent-1.2.0.js

Server
```
2015-06-16T20:31:08.104Z - warn: [gme:server:standalone] expressFileSending failed for: /home/hakan/github/webgme/webgme/src/client/lib/superagent/superagent-1.1.0.js: Error: ENOENT, stat '/home/hakan/github/webgme/webgme/src/client/lib/superagent/superagent-1.1.0.js'
```
Client, get error
```
GET http://localhost:8888/lib/superagent/superagent-1.1.0.js 
```

**Comment by lattmann** [comment]
Who is trying to load it?

`https://github.com/webgme/webgme/pull/406/files` - you should not change it to 1.1.0, we should figure out who is loading it and change it there.

**Comment by pmeijer** [comment]
It's in src/client/js/main.js

**Comment by lattmann** [comment]
Right, sorry, i missed that, i did a grep for superagent-1.1.0.... please add it to here: https://github.com/webgme/webgme/blob/master/src/client/lib/superagent/UPGRADE#L18
