### ISSUE TITLE
Browser crashes due autorouter

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#412]
When the AutoRouter is selected, the browser crashes while trying to show the object at ROOT > tos > platforms > exp430 > hardware > leds > PlatformLedsC > HplMsp430GeneralIOC in the project at https://drive.google.com/file/d/0B6icounl9q69VDVLNTVVWDhfcmc/view?usp=sharing

There are no messages logged at server or client side.

![aw snap](https://cloud.githubusercontent.com/assets/5684384/8194940/9ae072f0-1444-11e5-8976-14d7cec165ca.png)

**Comment by brollb** [comment]
@hakantunc Can you give me a mongodump instead? Your project is too large for me to import.
![a27_problem](https://cloud.githubusercontent.com/assets/4982789/8376400/75c53070-1bcc-11e5-9aef-1bb87c16748b.png)

**Comment by lattmann** [comment]
@brollb you may change this number to get around the file size limit. If you change it do it only locally please.

**Comment by hakantunc** [comment]
You should import the file directly to the mongo. It is generated with mongoexport. WebGME didn't allow me to export the project.

**Comment by brollb** [comment]
@hakantunc @lattmann Thanks, I will check it out!

**Comment by brollb** [comment]
@lattmann If I try to import using the web ui, the browser crashes (after increasing the max file size, of course)

@hakantunc I am having some trouble finding the file after importing into mongo... I will give it another try tomorrow and see if I can get this fixed.
