### ISSUE TITLE
Client improvement: be able to open a project with a specific branch

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#434]
Right now, the client always loads 'master' (or if it doesn't exist, one at random). It would be nice to be able to choose, so we don't pay the performance penalty

**Comment by pmeijer** [comment]
Kevin, would you like it to fall back on master and then on the first found one if the given branchName does not exist? Or return with error?

**Comment by ksmyth** [comment]
If branchName is specified and does not exist, it should be an error.
