### ISSUE TITLE
Autorouter auto download does not work with Safari

### ISSUE THREAD

**Issue by lattmann** [webgme/webgme#463]
If you set the debug flag in the config to `true` and cause to crash the autorouter, then it should download a crash report file. Using Safari it opens a page with the content of the file instead downloading it.

**Comment by ksmyth** [comment]
:+1:

**Comment by brollb** [comment]
I believe this modification will update the "download" function on line 586 of ConnectionRouteManager3.js (https://github.com/webgme/webgme/blob/master/src/client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js)

**Comment by kecso** [comment]
do we have a model where AR would likely crash?
right now I was unable to reproduce a crash.

**Comment by brollb** [comment]
You can probably change the code to get it to crash (like add a random variable somewhere. I like the variable name "crashAndBurn;" - it's self documenting ;) )
