### ISSUE TITLE
Easy way to clone a project

### ISSUE THREAD

**Issue by azeey** [webgme/webgme#47]
This would be useful for testing plugins. The only way to do this right now seems to be to export the project and import it again.

**Comment by volgy** [comment]
It would be great, if this could be used/triggered from a properly formatted URL ('Try' link)

**Comment by ksmyth** [comment]
I have a service to copy a project:
https://gist.github.com/ksmyth/e119642ce02d15575f37

**Comment by kecso** [comment]
I have created two short specification for proposed functionalities:
https://github.com/webgme/webgme/wiki/specSeedProject
https://github.com/webgme/webgme/wiki/specFork

**Comment by lattmann** [comment]
Looks good to me. Made minor changes.

**Comment by pmeijer** [comment]
I think it's implied but just to clarify;

To fork a project the user needs read access to that project and the user forking gets full right to the new project.

Correct?

**Comment by kecso** [comment]
Yes.
Additionally, the user has to have 'create' rights but I think that was stated explicitly.
Should I clarify it in the document?

**Comment by ksmyth** [comment]
specSeedProject/Parameters: for performance, I'd add a "squash" parameter. true => branches have 1 commit and lose other history

**Comment by kecso** [comment]
shouldn't we use some other name?
I mean for this functionality we have to create new commits for all the branches that have no history whereas the squash would mean to squash a trace of history into a single commit by pointing it to the original 'predecessor' if the first commit in the squash

**Comment by volgy** [comment]
Can't we merge these two "services"? Sorry, I do not see the fundamental difference.

**Comment by kecso** [comment]
In the fork you copy the whole project while in the seed, you just create a new one with a single branch from a snapshot.
Fork can be done solely with mongoDB queries, while the seed needs the interpretation of the data model (or the serialized format).
I would even add, that in the 'distant' future we might want to allow the fork to be a 'living' connection among projects letting to user to easily synchronize or even to add changes to the original project (as in case of Git).

**Comment by lattmann** [comment]
Patrially resolved in v0.9.0 release.
