### ISSUE TITLE
"Export branch" runs afoul of Chrome's popup blocker

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#480]
e.g.
http://editor.dev.webgme.org/?project=demo%2BSignalFlowSystem&branch=master&node=%2F682825457&visualizer=ModelEditor&aspect=All&selection=

![image](https://cloud.githubusercontent.com/assets/1047813/9226065/73651b80-40d2-11e5-82bc-9121de2a6626.png)

**Comment by pmeijer** [comment]
Closed by #523
