### ISSUE TITLE
mongo.js openDatabase should be refcounted

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#482]
mongo.js:

    if (mongo === null) {
        logger.debug('Connecting to mongo...');
        // connect to mongo
        mongodb.MongoClient.connect(gmeConfig.mongo.uri, gmeConfig.mongo.options, function (err, db) {
            if (!err && db) {
                mongo = db;

1. What happens if you call openDatabase twice in a row? (two connections are opened, one is lost and never closed)
2. What happens after this:

    client1Storage.openDatabase()
    // elsewhere
    client2Storage.openDatabase()
    client1Storage.closeDatabase()
    client2Storage.loadObjects(...)
    client2Storage.closeDatabase()

(client2Storage throws an error that the database hasn't been opened, even though it has and it hasn't yet called closeDatabase())

Suggested solution: keep a refcount in mongo.js. openDatabase increments it; if the ++refcount is 1, create a promise. If ++refcount > 1, return that promise. closeDatabase decrements it; if --refcount is 0, the mongo connection is closed.

**Comment by pmeijer** [comment]
Kevin I've created a branch to address this issue.
Just to clarify your example. The client storages can't close the database anymore, so your example2 would apply to the case when you pass the same mongo instance into two different server-storages (safestorage.js) and perform those steps. Or if you your storage instances are the same.

I tried to guard against a mix of multiple synchronous closeDatabase and openDatabase calls, but cannot guarantee that all those cases are handled.
