### ISSUE TITLE
Blob clients in workers raises DEPTH_ZERO_SELF_SIGNED_CERT when https enabled.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#521]
Workaround is to set:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

in `src/server/worker/simpleworker.js`.

**Comment by ksmyth** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED` is ill-advised. What if a plugin makes an https request to an external website? Then it is insecure.

I think it is better to explicitly add certs to trust. I did this for the executor-worker at https://github.com/webgme/webgme/blob/master/src/server/middleware/executor/worker/node_worker.js#L92-L101

**Comment by pmeijer** [comment]
Cool, thanks Kevin.

**Comment by pmeijer** [comment]
With #739 merged, this is no longer needed.
