### ISSUE TITLE
Enable option to add/upload SVG icons to the project

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme#635]
Currently there is no way to add your own icons to the icon set. How can one go about it?

**Comment by yogeshVU** [comment]
So what was the change done here? And how could one use this feature? thanks!

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/tree/master/config#visualization

You can add a path to a directory with svgs and they will be copied over and available when the server starts.
