### ISSUE TITLE
More information about the projects

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#677]
It would be great if we could have more information about the projects in the projects' list. For instance, we can have the last modified time of the projects.

**Comment by hakantunc** [comment]
In addition, we can have a search field which filters out the projects as we type.

**Comment by pmeijer** [comment]
I've added info about when the project was viewed and modified (through the websockets).
It's displayed in the ProjectDialog, where you can order based on the info and use the filters as before (by name). I haven't added a search bar in this Issue, when you create a new project it filters based on the first character though. The search bar is put on the back-log for now.

The ProjectNav orders projects based on when they were modified.
