### ISSUE TITLE
Executor feedback during execution

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#686]
It would be useful if executors could be queried while they are running for their stdout and stderr logs. This could provide the users progress feedback, etc.

**Comment by pmeijer** [comment]
I agree that the workers should provide more feed-back. Not sure if the stdout/err is the right channel though. If by user you mean users in the UI, then I think it's better that they send it via the web-sockets (which was introduced in #667 specifically for plugins, but it's written to support different types of notifications too) -that way they can target specific sockets or rooms.

**Comment by pmeijer** [comment]
Oh, for some reason I was thinking about the regular workers...
