### ISSUE TITLE
Mis-placed bumps

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#747]
As you can see,
![broken-bumps](https://cloud.githubusercontent.com/assets/211644/11787935/fd7e4b38-a253-11e5-9c39-0e0bae23893d.png), the bumps are not being placed correctly.

-----------------------
Chromium Version 47.0.2526.73 Ubuntu 14.04 (64-bit)

> $ npm start

>> webgme@1.3.0-beta1 start /home/feisele/webgme/webgme
>> node ./src/bin/start_server.js

> 2015-12-14T16:08:43.082Z - info: [gme:server:standalone] Valid addresses of gme web server:   http://127.0.0.1:8888  http://129.59.105.147:8888  http://10.67.12.152:8888
> 2015-12-14T16:08:43.168Z - warn: [gme:server:auth:gmeauth] Guest access can be disabled by setting gmeConfig.authentication.allowGuests = false
> 2015-12-14T16:08:43.169Z - info: [gme:server:auth:gmeauth] Guest account:  
> { metadata: 
>    { _id: 'guest',
>     canCreate: true,
>     email: 'guest',
>     orgs: [],
>     projects: { 'guest+junk': [Object] },
>     siteAdmin: null,
>     type: 'User' } }
>2015-12-14T16:08:43.968Z - info: [gme:server:worker:simpleworker:pid_23012] initialized worker
>2015-12-14T16:27:19.573Z - info: [gme:server:worker:simpleworker:pid_23012:WorkerFunctions] seedProject
>2015-12-14T16:27:19.821Z - info: [gme:server:worker:simpleworker:pid_23012:WorkerFunctions] seeding [96e267f9d896d6bcabe78e90818e8abc90195a3a] to [guest+feature_model] completed
>2015-12-14T16:27:20.127Z - info: [gme:server:worker:simpleworker:pid_23799] initialized worker
>2015-12-14T16:27:20.134Z - warn: [gme:server:standalone:serverworkermanager] worker 23799 has exited abnormally with code 0

**Comment by pmeijer** [comment]
Brian, I put you as assignee since this seems to be an autorouter issue. Could it be that it's using the bumps from the initial (RouteManager2) calculation?

**Comment by phreed** [comment]
I am unclear if this was supposed to be fixed in v1.6.0 or not.
In any case it is not.
![screenshot from 2016-03-21 13 09 33](https://cloud.githubusercontent.com/assets/211644/13929134/a7212390-ef66-11e5-8b4a-fc89402c0349.png)

**Comment by brollb** [comment]
@pmeijer I think you are correct about the placement problems. I can check this out sometime but it has been a lower priority of mine. As far as autorouting goes, my main priority currently is https://github.com/webgme/autorouter/issues/3; I haven't been addressing many of the other autorouting issues (unless they are major) because this issue will change the autorouter API and consequently, much of `ConnectionRouteManager3` (which is likely where this fix would reside)

**Comment by phreed** [comment]
This is not a big problem for me and as far as I am concerned does not need to be fixed.
However, it looks bad.
Maybe just turning it off, and removing the button to turn it on, until it is fixed.

**Comment by pmeijer** [comment]
Bumps are no longer available on the UI
