### ISSUE TITLE
Instance target bug

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#772]
When I'm importing a project, I'm getting tens of ```error handling needed???!!!???``` messages. Eventually, it looks like it imports the project on the client side. However, the imported project has broken connections. You can check ROOT > apps > Blink > BlinkAppC for an example after importing this: https://drive.google.com/file/d/0B6icounl9q69akgwdnEzaFFHLTA/view?usp=sharing

**Comment by pmeijer** [comment]
This seems related to the import issue Nag talked about.

**Comment by kecso** [comment]
I renamed the issue as the origin of the error is the use case, when a relation that's target is a shallow instance (it doesn't hold any additional info) is being exported and imported.
During the export we cannot create a proper id of the target that could be used during the import, that is why the error occurs.

**Comment by pmeijer** [comment]
Closed by #778
