### ISSUE TITLE
Server side plugins with dependencies

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#779]
When trying to run a server side plugin which uses a server side library through the plugin manager in WebGME, the client side throws error that it cannot load the dependent library even though I want to run it on the server side.

It would be nice to be able to run these kinds of plugins using the plugin manager in WebGME.

**Comment by pmeijer** [comment]
Where in your plugin do you require the server side dependencies?
If within in the `define([...], function(..{` part, you could move it to e.g. the main function. (It would probably fit better in the constructor, but currently (and probably unnecessarily) the client side also instantiates all the plugins.)

**Comment by hakantunc** [comment]
I tried this too. I get the following error:
```Error: Module name "path" has not been loaded yet for context: _. Use require([])(…)```

This is from a module that the plugin loads indirectly.

**Comment by pmeijer** [comment]
This worked for me, within main:

`var path = requirejs('path');`

If I execute the plugin on the client I get the same error as you..

**Comment by hakantunc** [comment]
There are some other files that the plugin uses. I get this error for these files even though I use the ```require``` or ```requirejs``` function as late as possible.

Eventually, I'll run this plugin with a custom trigger and won't have this issue; however being able to run server side plugins through the plugin manager might be helpful for other use cases in future.

**Comment by pmeijer** [comment]
Can you link to the code? This should definitely be possible..

**Comment by pmeijer** [comment]
Hakan can you confirm that this isn't an issue?

**Comment by hakantunc** [comment]
Yes, this is not an issue as long as you require your modules within main. Thanks.
