### ISSUE TITLE
URL query for node is not working for paths with non-numbers.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#785]

**Comment by pmeijer** [comment]
The REST calls using paths should probably be checked too.

**Comment by lattmann** [comment]
For the URL query parsing we should probably use a 'well-tested' library like:
- https://medialize.github.io/URI.js/
- https://www.npmjs.com/package/URIjs

instead of this magical regexp: https://github.com/webgme/webgme/blob/master/src/client/js/util.js#L107-L114
