### ISSUE TITLE
Don't require auth for js

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme#81]
Please don't require auth for js scripts, e.g.

    curl -v http://kms56:8888/lib/require/require.min.js
    * timeout on name lookup is not supported
    * About to connect() to kms56 port 8888 (#0)
    *   Trying 129.59.105.52...
    * connected
    * Connected to kms56 (129.59.105.52) port 8888 (#0)
    > GET /lib/require/require.min.js HTTP/1.1
    > User-Agent: curl/7.26.0
    > Host: kms56:8888
    > Accept: */*
    >
    < HTTP/1.1 302 Moved Temporarily
    < X-Powered-By: Express
    < Location: /login
    < Vary: Accept
    < Content-Type: text/plain
    < Content-Length: 40
    < Set-Cookie: webgmeSid=s%3AbqkkTjqnfoPaHQcnUx9Igbmn.y2yZ8aVd0qPUX9szFlpaQYPa9vtv8SPFHUbuakq6XrQ; Path=/; HttpOnly
    < Date: Fri, 25 Jul 2014 18:24:55 GMT
    < Connection: keep-alive
    <
    Moved Temporarily. Redirecting to /login* Connection #0 to host kms56 left intact
    * Closing connection #0

**Comment by lattmann** [comment]
Test cases were added. Please confirm that if all tests would pass that would resolve this issue.

**Comment by ksmyth** [comment]
I think the tests cover everything
