### ISSUE TITLE
Dragging a node from the tree-browser w/o selecting it creates another node.

### ISSUE THREAD

**Issue by amoghskulkarni** [webgme/webgme#838]
The instances of the entities in right-hand pane cannot be created, unless and until the entity being created instance of is expanded.

E.g. My metamodel -
![meta](https://cloud.githubusercontent.com/assets/11549656/13124169/8755b468-d585-11e5-894c-d11ea7071702.PNG)
In my root -
![root](https://cloud.githubusercontent.com/assets/11549656/13124211/c6f8c9fc-d585-11e5-85e4-bf966401bef4.PNG)
In which A1 and B1 are the instances created by dragging A and B from the left-hand pane. B1 contains C1 created in similar fashion.

The problem shows up when I try to create instance of B1 inside A1, by dragging B1 from right pane. Screen is turned red showing that the operation is not allowed, when actually it is (by the metamodel rules).
When I expand B1 in the right-hand pane and try the operation again, it is allowed.

(If B1 does not contain anything, the operation is not allowed at all - because, of course, we are not allowed to expand B1 in the right-hand pane)

**Comment by pmeijer** [comment]
Can you send your example model?
I tried to reproduce it and it works here.

![image](https://cloud.githubusercontent.com/assets/6518904/13125022/2376f26e-d589-11e5-9fac-5db9cd90fb93.png)

**Comment by amoghskulkarni** [comment]
Adding .zip file containg .json file of my project.

[guest+test_master.zip](https://github.com/webgme/webgme/files/135188/guest.test_master.zip)

These are my screenshots:
When B1 not expanded -
![notallowed](https://cloud.githubusercontent.com/assets/11549656/13125425/1c2613ee-d58b-11e5-910b-3647e250b0be.png)
When B1 is expanded -
![allowed](https://cloud.githubusercontent.com/assets/11549656/13125431/21af8aa2-d58b-11e5-832c-7fb0a165aa7b.png)

**Comment by pmeijer** [comment]
I see the issue now. There's a discrepancy between what is displayed as being dragged and what is evaluated (a and potentially created).
What will/would be created is what is selected (highlighted by blue) in the tree. 

It's a bug and I will fix it, for now just make sure to select the object first.

**Comment by amoghskulkarni** [comment]
Sure. Thanks.

**Comment by pmeijer** [comment]
Closed by #840
