### ISSUE TITLE
Hover response is too aggressive

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#843]
There are a number of places where the hover behaviour brings up menus.
1) This is not typical behavior,  in order to open a menu a click is typically required.
2) Frequently this is a near miss and the menu covers what you really wanted to select.
Specifically, the plugin selector is right below the GME menu which covers the plugin selector.
3) Hover should really only offer hints.

**Comment by lattmann** [comment]
Fixed in #848

**Comment by phreed** [comment]
https://www.google.com/design/spec/components/menus.html#menus-behavior
The behavior I described is not just my preference.

**Comment by phreed** [comment]
Here is the detail on adding your own CSS: 

<style/immortals.css>
ul.dropdown-navigator > li:not(.separator):hover > .hierarchical-menu {
  visibility: none; }

ul.dropdown-navigator > li:not(.separator):active > .hierarchical-menu {
  transition-delay: 0.0s;
  visibility: visible;
  opacity: 1; }

<config/config.default.js>  (inserted before validateConfig(config))

config.requirejsPaths["style"] = './style/';
config.visualization.extraCss = ['style/immortals.css'];

**Comment by phreed** [comment]
Here is a sample of how this could work.
https://jsfiddle.net/Cerebrl/uhykY/
The existing :hover rule gets in the way.
The example in the previous comment is close but not quite.

**Comment by pmeijer** [comment]
You can be more specific in your css rule if you're having issues overwriting the rules from the dropdown navigator.
![image](https://cloud.githubusercontent.com/assets/6518904/14025730/879a9b60-f1bd-11e5-82aa-94a2c1abe0f9.png)

**Comment by phreed** [comment]
Could you make the .hierarchical-menu elements :focus-able by adding the tabindex="0" to each occurrence?

**Comment by phreed** [comment]
I made this change in https://github.com/vu-isis/isis-ui-components/commit/19ae0f7223167702be88cabfb876cff5bc7b4880

**Comment by lattmann** [comment]
Thanks @phreed, I made a new release v0.2.18. Please checkout this branch issue/843_dropdown_menu_on_click and see if it works as expected, then we merge it.
