### ISSUE TITLE
SVG Decorator items do not align correctly

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme#862]
With SVGDecorator, the objects do not align correctly. In the screenshot, all the objects has position registry set x: 50.

![align](https://cloud.githubusercontent.com/assets/5684384/13395414/2d858016-deb4-11e5-9d63-16a70348ad39.png)

You can find this image location at ROOT > tos
Project: https://drive.google.com/file/d/0B6icounl9q69eDlnYlhQS01Cdmc/view?usp=sharing

**Comment by lattmann** [comment]
Can you try to rename platforms to p? I think it aligns the outer bounding boxes, which could be bigger than the icons itself.

**Comment by hakantunc** [comment]
It looks so. I think it would be more intuitive and easier to align objects if they were aligned by the icons.

![systemsystem](https://cloud.githubusercontent.com/assets/5684384/13406358/a74dfc6e-dee8-11e5-95f3-e9e6bf5a760b.png)

**Comment by lattmann** [comment]
Agreed, I wanted to double check that the alignment feature still works and positions are set correctly.
We need to get the bounding box without the label/name.
