### ISSUE TITLE
Performance issues with Istvan's Resos models

### ISSUE THREAD

**Issue by nabana** [webgme/webgme#87]
GME spends quite some time (3-4s) thinking on stuff when moving boxes in a relatively innocent looking view. Istvan has the full details. Here are a couple of screen shots from the profiling snapshot.

![profile-heavy](https://cloud.githubusercontent.com/assets/949040/3784440/6e2a2f12-19b8-11e4-9861-1a9f8fc2788c.png)
![profile-zoomed-in](https://cloud.githubusercontent.com/assets/949040/3784441/6e2dda54-19b8-11e4-9d58-b63d167be26c.png)

Please look into it, when you can. Thanks.

**Comment by kecso** [comment]
the problem is outdated. reopen in case of new and still valid data or create new one if performance issues arise with other projects
