### ISSUE TITLE
In addition to 'alignment' support 'distribute'

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#870]
The movement icon/menu has move and align actions but no distribute.

![movement](https://cloud.githubusercontent.com/assets/211644/13473997/9cc29b98-e081-11e5-8828-09515b6c74df.png)

Something like what is found in this ...
![distribute](https://cloud.githubusercontent.com/assets/211644/13474296/f4b4d3f6-e082-11e5-97cf-8b58d7db40f1.png)

**Comment by pmeijer** [comment]
Noticed that our alignments are inverted.

**Comment by finger563** [comment]
Perhaps use cola.js or cytoscape.js to implement as in [plugin using cola to auto layout nodes with links between them](https://github.com/finger563/webgme-gridlabd/blob/master/src/plugins/ImportGLM/ImportGLM.js#L835) or [visualizer example to display compound nodes with edges using cytoscape](https://github.com/rosmod/webgme-rosmod/blob/master/src/visualizers/widgets/CommViz/CommVizWidget.js)
