### ISSUE TITLE
META Decorator attribute not updating

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#88]
META decorator not updating attribute type on change.

When I change the attribute from "string" to "float", it still says "string" on the object (though opening the edit panel again shows that it has changed to "float")

**Comment by brollb** [comment]
This can be replicated by opening the META editor and changing an existing attribute type without modifying anything else.

Changing the attribute...
![edit_attr_before](https://cloud.githubusercontent.com/assets/4982789/6177363/9f0e48aa-b2cb-11e4-834f-1accc5f70c81.png)

After (no change):
![edit_attr_after](https://cloud.githubusercontent.com/assets/4982789/6177366/a4f15d70-b2cb-11e4-890d-67c26901b7b2.png)

**Comment by lattmann** [comment]
@brollb please test the fix: issue/88_meta_editor_type_bug

**Comment by brollb** [comment]
Works as of https://github.com/webgme/webgme/commit/b2e579a09af5d70692c49cd02da32cdb0008326b
