### ISSUE TITLE
Symmetric "Plug-in Architectural Programmer's Guide" and "Annotated Examples"

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#883]
Getting into writing plug-ins for webGME is difficult for a few reasons:
  * The javascript full-stack is rapidly changing and it is not clear at what generation of it was extant for  webGME  There are a number of documents describing the different stacks, maybe there is one that could be referenced.
  * The high level architecture is covered fairly well by the white paper but it needs to be reduced to code examples. The presentation given to the MIC class is a good start on a "programmer's guide".
[WebGME-MIC.v3.pdf](https://github.com/webgme/webgme/files/168050/WebGME-MIC.v3.pdf)
  * The examples are not sufficiently documented and are not specifically referenced by the "programmer's guide".

Begin by dissecting the basic plugin example.
It would be interesting to drop the basic generated plugin code into a code review tool (like http://codebrag.com/ or jsfiddle).
Then annotate the additional architectural stuff (like requirejs) in preparation for being referenced by the "programmer's guide".
This would build on the comments which already annotate the basics (like introducing the core).

Is there a way of adding annotations to javascript so that a document can link to them?

**Comment by pmeijer** [comment]
For now use: https://github.com/webgme/webgme/wiki/GME-Plugins

**Comment by pmeijer** [comment]
https://github.com/webgme/webgme/wiki/Plugin-Step-by-Step-Tutorial

**Comment by phreed** [comment]
nice

**Comment by pmeijer** [comment]
@phreed: If you have time it would be appreciated if you can look through the [Step-by-Step tutorial](https://github.com/webgme/webgme/wiki/Plugin-Step-by-Step-Tutorial). If you have questions you can inline them. Feel free to correct my English.
