### ISSUE TITLE
Add tests for reassigning guids.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#889]
This is related to PR #886

**Comment by pmeijer** [comment]
Please check the coverage in the core for #882 too.

**Comment by pmeijer** [comment]
Will this be deprecated by the new library feature?

**Comment by kecso** [comment]
I haven't thought of it yet, but now that you say: yes it will be.
Should we close the issue then? (or create a new one to remove the whole functionality...)

**Comment by pmeijer** [comment]
See discussion above.
