### ISSUE TITLE
When deleting connectors from a crosscut the object is deleted (not just removed)

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#896]
Given a connector appearing in more than one crosscut (or the composition).
When that connector is removed from a crosscut it is removed from the model.
It is a bug if there is no way to remove an object from the crosscut without deleting it from the model.
This is true whether the connector was created in the particular crosscut or not.

[crosscut_removal_master.json.txt](https://github.com/webgme/webgme/files/180168/crosscut_removal_master.json.txt)

Copy the 'C' object into the crosscut. Then remove it. It is deleted from the model.
The behavior I expect is that when the last occurrence of an object is removed from
its owner, only then is it be deleted from the model.

**Comment by pmeijer** [comment]
Related to #869

**Comment by phreed** [comment]
Issue #869 relates to *what* is do be done when an element is deleted. 
This issue is related to *when* a node should be deleted and differentiating between a "delete" and a "remove-from-crosscut".

**Comment by pmeijer** [comment]
I see the issue but...
"The behavior I expect is that when the last occurrence of an object is removed from
its owner, only then is it be deleted from the model."
...is unfeasible since it would require the operation to load the entire project at removal. 

The quick fix would be to only clear the pointers of the connection and only remove the connection-node from the cross-cut (set).
A semi-quick-fix would be to offer the user the choice between the current behavior and the quick-fix.

**Comment by phreed** [comment]
Removing the connection-node from the cross-cut makes sense.
I am not sure what pointers would be cleared. The only pointers I can think of should be left alone.

**Comment by pmeijer** [comment]
I talk with Tamas about a solution and one way to do it could be to delete the actual connection-node iff the parent of the connection is the node defining the cross-cut.

**Comment by pmeijer** [comment]
...and the connection only exists in that particular "crosscut-tab" in that node.

**Comment by phreed** [comment]
As we discussed.
When a connector (or any object) is removed from a cross-cut:
 * if it is *not* owned by the cross-cut object then it is *removed* from the cross-cut
 * if the object *is* present in any other cross-cuts of the owner then the cross-cut object is *removed" from the cross-cut
 * if the object is *not* present in another cross-cut of the owner then the object is *deleted* from the model
