### ISSUE TITLE
User experience issue : adding connector to a crosscut

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#897]
It is difficult to know if preexisting connectors exists between objects.
The main purpose of crosscut views is to establish a context in which 
connectors can be managed.

The current implementation is great for adding new connectors.
If there are two objects A and B and there is no connector between them;
then adding a connector is trivial. 
If there are more than one type of A-B connector that can be created;
a list of the different connector types is presented.

Assume there is already a A-B connector in another crosscut.
It may be that the A-B connector is relevant to the current crosscut. 
Presently, the A-B connector can be copied from the tree into the crosscut.
The difficulty is in identifying that the connection exists and which one it may be.
The means for identifying the other A-B connectors is an unpleasant experience.
The problem only manifests itself by examination of the "conpoisition" view
which, in some cases, will automatically include the new connectors.

Suggestion:
Enhance the list of connector types presented during creation 
to include all existing A-B connections in addition to the creation options.

**Comment by pmeijer** [comment]
Do you use connector and connection interchangeably here?

**Comment by pmeijer** [comment]
![goto](https://cloud.githubusercontent.com/assets/6518904/13968761/82f8cdb0-f04c-11e5-946e-abf7a2f4e278.PNG)

Fred is this sufficient. Clicking on the GoTo item will open up the existing connection. From there you can locate the node in the tree-browser. (Currently only the path is display since the connection may or may not be loaded at the time of the menu creation.)

**Comment by pmeijer** [comment]
Currently if there is only one type of connection it is created automatically. With this change I would assume that the menu should at least pop up if there are existing connections. However would you like it to pop up even though there aren't any (and it that case display the only option 'Create connection...'?).

**Comment by pmeijer** [comment]
One more thing, do you have a better phrase than 'GoTo'? 'Open'?

**Comment by phreed** [comment]
Yes, that looks good. Open or use are both good verbs.

**Comment by pmeijer** [comment]
Closed by #906

**Comment by phreed** [comment]
There was more discussion on this issue.
The idea was not to go-to/open an existing connection but to select an existing connection for its inclusion in the cross-cut.

**Comment by pmeijer** [comment]
Can you file a separate issue for that?
