### ISSUE TITLE
Requiring text in plugin causes tests to fail

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#898]
When testing a plugin that uses the "text!" prefix the tests fail with error 

`Tried loading "text" at ... then tried node's require("text") and it traile failed with error: Error: Cannot find module 'text' to equal null `

**Comment by pmeijer** [comment]
Brian, is this possible when running a plugin at the server at all? Or is it just for the tests?

**Comment by brollb** [comment]
I just saw it when running the tests; I don't believe the requirejs config is set up correctly wrt the text plugin. Adding the following to my `globals.js` fixes it (but I think it should already be set up):

```
testFixture.requirejs.config({
    paths: {
        text: 'client/lib/require/require-text/text'
    }
});
```
