### ISSUE TITLE
When meta sheet is deleted, prompt the user what they like to do

### ISSUE THREAD

**Issue by nadand** [webgme/webgme#9]
Using the project from the tutorial. If you delete the meta sheet, you cannot create new models until the models are dragged back onto a meta sheet. The meta information is maintained in the models themselves and being on a sheet should not affect behavior. 

Before the deletion of the meta sheet.
![screen shot 2014-04-16 at 1 15 55 pm](https://cloud.githubusercontent.com/assets/6733280/2723400/eb4e350c-c593-11e3-91a1-6888ad5718fa.png)

After the deletion of the meta sheet.
![screen shot 2014-04-16 at 1 16 15 pm](https://cloud.githubusercontent.com/assets/6733280/2723404/f58f7e54-c593-11e3-9a1c-fdc7b099fada.png)

**Comment by lattmann** [comment]
Deleting a meta sheet could be ambiguous, what should be done.

1. if all elements are included on at least another meta sheet, then just delete the meta sheet
2. if at least one element (e.g. X and Y) is not included any other meta sheet then offer a few options to the user
 * Delete the meta sheet and __keep all__ meta rules for (X and Y)
 * Delete the meta sheet and __delete all__ meta rules for (X and Y)
 * Delete the meta sheet and __keep__ the meta rules for some object (X) and __delete__ for other ones (Y)
 * Cancel the delete operation and do not delete the meta sheet.
