### ISSUE TITLE
Crosscut visualizer does not automatically load nodes from other branches

### ISSUE THREAD

**Issue by nadand** [webgme/webgme#904]
Crosscuts that contain elements from other parts of the model not just under the model containing the crosscut does not load. The visualizer is only displaying the rotating loading icon. To load such crosscuts the user has to visit the containers of the models to get them loaded. After that the crosscut loads and display properly.

**Comment by kecso** [comment]
Could you provide an example?
Seemingly the fact, that the elements of the crosscut coming from distant part of the project is not enough to bring up the loading issue.

Thank you!

**Comment by pmeijer** [comment]
Andras, here is the decorator method for defining territories with children...

https://github.com/webgme/webgme/blob/master/src/client/js/Widgets/DiagramDesigner/DiagramDesignerWidget.DecoratorBase.js#L311-L313

..and here is an example where it's overwritten.

https://github.com/webgme/webgme/blob/master/src/client/js/Decorators/DecoratorWithPorts.Base.js#L18-L39

Let me know if this works for you - if so I will close the issue.

**Comment by pmeijer** [comment]
Turns out this was a decorator issue (see comment above for future references).
