### ISSUE TITLE
zoom +/- buttons with collapsible zoom slider

### ISSUE THREAD

**Issue by sperka** [webgme/webgme#907]
Would be great to have +/- buttons along with the zoom slider, google maps style. UX would increase significantly

**Comment by lattmann** [comment]
:+1: 

@sperka can you create a screenshot and attach to the issue?
Where the buttons should be located?
Below/above/next to zoom control?
Adding the buttons with photoshop would be fine and take a screenshot of that.

**Comment by sperka** [comment]
State 1: +/- zoom buttons by default
State 2: mouse hover shows popover with button to show slider
State 3: +/- zoom buttons with slider, and popover to hide slider

![zoombuttons](https://cloud.githubusercontent.com/assets/157324/13997617/f5c55002-f100-11e5-806f-2da8526033c4.jpg)

**Comment by lattmann** [comment]
Perfect, thanks.
