### ISSUE TITLE
Prototypal-Inheritance v. Class-Inheritance

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#910]
This issue is probably a usage question rather than a software problem.
If that is the case then this relates to the documentation rather than the software.

The biggest difference between desktop-GME and web-GME is in the integration of meta-rules into the model.
How would you recommend indicating that a node should be a proper part of the model-instance or existing only as part of the meta-model?
I do not think relying on the convention of their being in the "Language" folder is strong enough.
My current thought is to add an attribute on the Language folder called something like 'inheritance-type'.
Determining if the inheritance for a particular rule would involve climbing the containment tree until the 'inheritance-type' is found.
Does this sound like a good approach?

https://en.wikipedia.org/wiki/Prototype-based_programming

**Comment by kecso** [comment]
What would you like to achieve with such categorization (please give some detailed explanation why and how the indication would be used)?
- in Web-GME, any node can act as a type, and can be instantiated -> this means that there is no such thing as meta-model in the traditional sense
- in the basic UI we have the convention that there are nodes that are part of the 'language' (meaning they are members of a special set of the project's root), some functionality use this convention (like the part-browser) and there are inquiries that help to decide for every node if they are part of this 'language'

**Comment by phreed** [comment]
The question came from one of the project partners. They are wanting to generate Java classes from the model. How do they know which objects should/could be realized as Java classes?

**Comment by kecso** [comment]
In this case, I would suggest the use of the core.isMetaNode(node) function.
I believe they are generating the code with a plugin.
https://editor.webgme.org/docs/source/Core.html

**Comment by phreed** [comment]
core.isMetaNode() is a good indicator that a node is intended to be part of the meta-model.
It indicates that the object is a base-for-inheritance, but there are multiple types of inheritance. 
It is this ability to distinguish types of inheritance I am wondering about.
I am beginning to think that the type of inheritance is an optimization decision should be deferred until it can be reliably inferred.

**Comment by kecso** [comment]
There are no multiple types of inheritance in WebGME, so it is a bit unclear what you would like to infer.
If we assume, that you wish to 'model' different types (or at least different from the already existing prototypical one in the model) of inheritance, then you have basically two options:
- you can group your 'classCandidates' into a single folder (or sub-tree), and then having an attribute on the folder would suffice
- you can create a Mixin object, with the attribute of 'isClass', assign it to your FCO, and then you can set it true at every object that is a 'classCandidate' (as Mixins doesn't pass their data)

'If I misunderstood you, then please provide an example (like you did with the Java class) so I can better help you.'

**Comment by phreed** [comment]
The last post is exactly my point.
The two options sound viable, I will try both and see which one works better.
I did not realize that Mixins do not pass their data so that is good to know.
Thanks
