### ISSUE TITLE
Sync PropertyEditor with ObejctBrowser (TreeView) Selection

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#916]
This may be a usage question.
Is there a way to select an item from the ObjectBrowser and see its properties in the PropertyEditor?
Currently, I double-click on an item in the ObjectBrower which opens the object in the PropertyEditor but it also changes the visualizer to Composition with the context of the selected item.
The typical use-case is in using the visualizer to establish a working-context, and to update some property on an object without changing the working-context (i.e. visualizer).

**Comment by pmeijer** [comment]
Right click and click "Select Node"
![image](https://cloud.githubusercontent.com/assets/6518904/14086590/871c50f8-f4eb-11e5-869d-9b6445e4c23d.png)

**Comment by pmeijer** [comment]
This was added in 1.6.0

**Comment by phreed** [comment]
Based on use, SelectNode should be the default selection and OpenInVisualizer.

**Comment by pmeijer** [comment]
To clarify: You want the node to be selected (show up in the Property Editor) when you select (single-click) it in the tree-browser?

**Comment by phreed** [comment]
That is correct.  Similar to what happens when it is picked in the CompositionVisualizer.

**Comment by pmeijer** [comment]
The problem with that is the pointer widget in the Property Editor. If the node is auto-selected you won't be able to drag the node from the tree and set it as a target for a selected node.

**Comment by pmeijer** [comment]
The proposed behavior would prevent certain UI actions - instead right click and do Select node.
