### ISSUE TITLE
context menu should scroll if too large

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#93]
the context menu created when dragging an item from the object browser to the activeObject should scroll if too large for the screen.

![menu_should_scroll](https://cloud.githubusercontent.com/assets/4982789/4066412/a916cfac-2e23-11e4-981d-1156025e9b59.png)

**Comment by brollb** [comment]
This can be replicated (in a very simple case) by dragging an item from the object browser to the composition panel near the bottom. The menu should be modified (as laszlo suggested above) given the available space and the needed space.

![scrolling_context_menu](https://cloud.githubusercontent.com/assets/4982789/6177207/350541c6-b2ca-11e4-9edf-afac1799fea0.png)

**Comment by lattmann** [comment]
@brollb please test it, issue/93_context_menu_scroll branch.

**Comment by brollb** [comment]
Works as of https://github.com/webgme/webgme/commit/ec7dbdbb39cbbb23087a20f5de9ec70eefc56945
