### ISSUE TITLE
DocumentDecorator uses default classes when rendering onto Object

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#938]
These default classes (e.g. `h1`, `h2`, `ul`, `li`) may be over-ridden by other css styles and break the MarkDown rendering (only when displaying on the node in the visualizer).  Perhaps change the MD rendering to use custom class names to prevent them being over-ridden?

**Comment by pmeijer** [comment]
Did you experience any issues with this? Looking at the Epic-Editor code it looks like it parses the css files and sets the style directly onto the DOM-elements. So the Epic-Editor itself should be safe however currently the DocumentDecorator requires/loads the css files too which could affect other parts of the UI in a bad way.

**Comment by finger563** [comment]
yes, the epic editor is fine (i.e. its styling is always fine), but the document decorator shares style names with other commonly used styles (as mentioned above); I ran into this issue and can show you what it looks like if needed.

**Comment by pmeijer** [comment]
Closed by #951
