### ISSUE TITLE
Shift-(direction) should allow for unselect in object browser

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#94]
shift+(down arrow) allows multi select in the object browser but shift+(up arrow) doesn't de-select the item.

**Comment by brollb** [comment]
This can be replicated by selecting an item in the object browser and selecting objects above or below using shift+(arrow key)
![select_object_browser](https://cloud.githubusercontent.com/assets/4982789/6177261/c07eb552-b2ca-11e4-89c2-722a38db3099.png)

**Comment by lattmann** [comment]
This works for me using the master branch.

**Comment by lattmann** [comment]
@brollb  please test it, and see my detailed comment.

**Comment by brollb** [comment]
It's a little weird when you are using shift+up then use ctrl+mouse to an item below your starting item as pressing shift+up again doesn't highlight the given items (as you are moving toward the selectionStartNode).

Maybe ctrl+mouse click should update the selectionStartNode to the given clicked node?

**Comment by brollb** [comment]
Shift arrow keys works as of https://github.com/webgme/webgme/commit/d5ae572c7a0a14857eb5dd58297f3e9bc844d98e
