### ISSUE TITLE
When checking project constraints the links to offending nodes are broken.

### ISSUE THREAD

**Issue by finger563** [webgme/webgme#948]
This issue occurs even when plugins try to call `createMessage` with a reference to a specific nodeObject.  Clicking on the link in either case doesn't do anything.

**Comment by pmeijer** [comment]
This works for me.. Do you have the same project open as when you ran the plugin?
Do you already have the node open?

When you say doesn't do anything, doesn't it even close the dialog?

**Comment by finger563** [comment]
yes the project is the same and no the node is not already open;  Correct, it does not close the dialog or show any indication that anything has happened.

**Comment by pmeijer** [comment]
Are there any errors logged to the console? If not, maybe you can just show me tomorrow.

**Comment by finger563** [comment]
No errors are logged anywhere I've seen, either on the server console or the client console. 

William Emfinger 
Post-Doctoral Researcher
Vanderbilt university institute for software integrated systems 
16th avenue s Nashville TN 37212

**Comment by pmeijer** [comment]
Closed by #965
