### ISSUE TITLE
Connection Not Redrawn

### ISSUE THREAD

**Issue by phreed** [webgme/webgme#969]
Adding a connection object to a composition and then assigning objects as 'src' and 'dst' does not immediately draw the connection as an edge.
Refreshing the browser causes the connection to be rendered as an edge.

**Comment by pmeijer** [comment]
I have a proposed fix for this issue at, can you try it out?

https://github.com/webgme/webgme/tree/issue/969_connection_not_redrawn

This also fixes the other direction, i.e. when removing the src/dst pointers the connection is drawn as a box.

**Comment by phreed** [comment]
Yes, It seems to fix this issue.
I do see what it does for the other issue.

**Comment by pmeijer** [comment]
Closed by #990
