### ISSUE TITLE
Moving programmatically created meta nodes causes error

### ISSUE THREAD

**Issue by brollb** [webgme/webgme#973]
After I programmatically create meta nodes on the meta sheet (w/o setting a position), moving a node throws an error

![meta-movement-bug](https://cloud.githubusercontent.com/assets/4982789/14754700/ac01cf40-08a2-11e6-8510-edc56ff64238.png)

**Comment by pmeijer** [comment]
A workaround for now is to add the registry position.

**Comment by finger563** [comment]
Can you elaborate on this?  I'm using `setRegistry` on the node for the `position` registry, but it only sets the position in the composition, not on the meta sheets that the node has been associated with.

**Comment by pmeijer** [comment]
Closed by #1025
