### ISSUE TITLE
Gathering collection information for a node inside a complex instantiation crashes the core

### ISSUE THREAD

**Issue by kecso** [webgme/webgme#982]
Given the following scenario:
- type/node A
- type/node B that has a child of type A (that is an instance of the node A)
- type/node C
- type/node S that has a child of type B (that is an instance of node B)
- type/node D that has a child of type C and a child of type A and the C typed child refers to A typed child with pointer 'ref'
- type/node V that has a child of type S and a child of type D

In this setup, if we create an instance of type V (let's call it V'), then when we ask the names of the collections of its A typed grandchild, we should receive the list ['ref']. Right now, such question ends in a crash inside the Core.

**Comment by pmeijer** [comment]
Would you mind attaching the model described above?

**Comment by kecso** [comment]
[issue982.zip](https://github.com/webgme/webgme/files/241009/issue982.zip)

here it is.
for verification it should be enough to browse through V' and check for the meta types of every node inside
