### ISSUE TITLE
Minor - Correcting link to API documentation in README

### ISSUE THREAD

**Issue by patrickkerrypei** [webgme/webgme#997]
Current link goes to [current](https://anypoint.mulesoft.com/login/#/signin)
Updated link should be: [updated](https://editor.webgme.org/developer/api)

**Comment by pmeijer** [comment]
Patrick, which link is this? There's one that should point to mulesoft's editor. That's where we maintain the API docs.

**Comment by patrickkerrypei** [comment]
I previously thought it was for http://github.com/webgme/webgme/tree/master/src/server/api
but I see that it's because the API docs are maintained there.
